import {createRequire} from 'node:module';
import {existsSync,readFileSync,readdirSync,mkdirSync,realpathSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const base=resolve(dirname(fileURLToPath(import.meta.url)),'..');
let Miniflare;try{({Miniflare}=await import('miniflare'));}catch{const r=createRequire(realpathSync(resolve(base,'node_modules/wrangler/package.json')));({Miniflare}=r('miniflare'));}
const root=resolve(base,'dist/server');if(!existsSync(resolve(root,'index.js')))throw new Error('Built game missing. Run npm run build first.');
const files=readdirSync(root,{recursive:true}).filter(f=>f.endsWith('.js'));const modules=['index.js',...files.filter(f=>f!=='index.js')].map(f=>({type:'ESModule',path:resolve(root,f)}));
const verify=process.argv.includes('--verify'),data=verify?resolve(base,'.sites-runtime/local-test-data'):resolve(base,'saved-game');mkdirSync(data,{recursive:true});
const options={modules,modulesRoot:root,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],host:'127.0.0.1',port:verify?0:8787,d1Databases:{DB:'aetheria-local'},d1Persist:data,assets:{directory:resolve(base,'dist/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:true,has_user_worker:true}}};
async function boot(){const m=new Miniflare(options),db=await m.getD1Database('DB');for(const sql of readFileSync(resolve(base,'drizzle/0000_talented_epoch.sql'),'utf8').split('--> statement-breakpoint'))await db.exec(sql.trim().replace('CREATE TABLE ','CREATE TABLE IF NOT EXISTS ').replace(/\n/g,' '));return m;}
let mf=await boot();if(verify){const origin='http://localhost:8787';const home=await mf.dispatchFetch(origin);assert.equal(home.status,200);const r=await mf.dispatchFetch(origin+'/api/game',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({join:true,name:'로컬검증',classId:0})});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie').split(';')[0],player=(await r.json()).player;const wsResponse=await mf.dispatchFetch(origin+'/api/socket',{headers:{Upgrade:'websocket',Origin:origin,Cookie:cookie}});assert.equal(wsResponse.status,101);wsResponse.webSocket.accept();wsResponse.webSocket.close();await mf.dispose();mf=await boot();const reloaded=await mf.dispatchFetch(origin+'/api/game',{headers:{Cookie:cookie}});assert.equal((await reloaded.json()).player.id,player.id);await mf.dispose();console.log('PASS: portable local server, WebSocket and disk persistence after restart');}else{await mf.ready;console.log('\nAetheria local game: http://127.0.0.1:8787\nSaved characters: saved-game/\nPress Ctrl+C to stop.\n');const stop=async()=>{await mf.dispose();process.exit(0);};process.on('SIGINT',stop);process.on('SIGTERM',stop);}
