import {test} from 'node:test';import assert from 'node:assert/strict';
import {createWorld,newPlayer,applyInput,tickWorld,stats} from '../server/engine';
import {hurtPlayer,damageMonster} from '../server/combat';
import {beginnerProtected} from '../shared/beginner';
import {tutorialReady} from '../shared/tutorial';
import {PROMOTION_TRIALS} from '../shared/promotion';
import {cashInput} from '../server/cash';import {DAMAGE_SKINS} from '../shared/damage-skins';
const now=1800000000000;
function setup(level=1,cls=0){const w=createWorld(now),p=newPlayer('beginner','초보',cls,now);w.players[p.id]=p;p.level=level;p.zone=1;p.x=700;p.y=600;p.hp=stats(p).hp;return {w,p};}
test('all unenhanced classes LV1–20 survive bursts; promotion, LV21 and raids end protection',()=>{assert.equal(PROMOTION_TRIALS[0].level,20);for(const lv of [1,3,10,20])for(const cls of [0,1,2]){const {w,p}=setup(lv,cls),max=stats(p).hp;for(let i=0;i<12;i++)hurtPlayer(w,p,1000,now+i*20);assert.ok(p.hp>=max-Math.floor(max*.065));assert.ok(beginnerProtected(p));const hp=p.hp;p.promotionTier=1;hurtPlayer(w,p,1000,now+300);assert.ok(p.hp<hp);assert.equal(beginnerProtected(p),false);}const {p}=setup(21);assert.equal(beginnerProtected(p),false);p.level=10;p.zone=25;assert.equal(beginnerProtected(p),false);});
test('beginner attack and XP boost require no enhancement',()=>{const a=setup(),b=setup();b.p.promotionTier=1;const ma=a.w.monsters.find(m=>m.zone===1)!,mb=b.w.monsters.find(m=>m.zone===1)!;ma.x=mb.x=740;ma.y=mb.y=600;ma.hp=mb.hp=1000;damageMonster(a.w,ma,a.p,10,now);damageMonster(b.w,mb,b.p,10,now);assert.equal(ma.hp,984);assert.equal(mb.hp,990);damageMonster(a.w,ma,a.p,9999,now+1000);damageMonster(b.w,mb,b.p,9999,now+1000);assert.equal(a.p.xp,b.p.xp*2);assert.equal(a.p.enhancements,undefined);});
test('beginner field recovery ends after promotion',()=>{const {w,p}=setup(3);w.monsters=[];p.hp=10;p.mp=0;tickWorld(w,now+500);assert.ok(p.hp>10);assert.ok(p.mp>1.4);p.promotionTier=1;const hp=p.hp;tickWorld(w,now+1000);assert.equal(p.hp,hp);});
test('tutorial verifies real movement, skill, quest and kills; level and pet reward are one-time',()=>{const {w,p}=setup();p.zone=0;let time=now,seq=0;const send=(body:any)=>applyInput(w,p,{...body,seq:++seq},time+=1000);send({action:'tutorialNext',value:6});assert.equal(p.tutorial!.stage,1);send({action:'tutorialNext',value:6});assert.equal(p.tutorial!.stage,1);send({moveX:120,moveY:0});assert.ok(tutorialReady(p));send({action:'tutorialNext'});send({skill:0});assert.equal(p.tutorial!.usedSkill,false);send({action:'travel',value:1});send({skill:0});assert.equal(p.tutorial!.usedSkill,true);send({action:'tutorialNext'});send({action:'quest',value:0});send({action:'tutorialNext'});assert.equal(p.tutorial!.stage,4);send({action:'tutorialNext'});assert.equal(p.tutorial!.stage,4);for(let i=0;i<3;i++){const m=w.monsters.find(m=>m.zone===1)!;p.x=700;p.y=600;m.x=740;m.y=600;m.hp=1;p.cd[0]=0;send({skill:0,tx:740,ty:600});}assert.ok(tutorialReady(p));send({action:'tutorialNext'});assert.ok(p.level>=2);send({action:'tutorialNext'});send({action:'tutorialNext'});assert.deepEqual(p.pets,[0]);assert.equal(p.petId,0);assert.equal(p.petAutoLoot,true);assert.equal(p.tutorial!.completed,true);const xp=p.xp;send({action:'tutorialStart'});send({action:'tutorialNext'});assert.deepEqual(p.pets,[0]);assert.equal(p.xp,xp);});
test('gold skin buys charge once and reject cash-only or unowned equip',()=>{const {w,p}=setup();let seq=0;const send=(body:any)=>applyInput(w,p,{...body,seq:++seq},now+seq*1000);assert.equal(DAMAGE_SKINS.filter(s=>s.currency==='gold').length,2);assert.equal(DAMAGE_SKINS.filter(s=>s.currency==='cash').length,3);send({action:'damageBuy',value:1});assert.equal(p.damageSkins!.length,0);p.gold=2000;send({action:'damageBuy',value:1});assert.equal(p.gold,1400);send({action:'damageBuy',value:1});assert.equal(p.gold,1400);send({action:'damageBuy',value:3});send({action:'damageEquip',value:3});assert.equal(p.damageSkinId,1);send({action:'damageBuy',value:2});assert.equal(p.gold,200);send({action:'damageEquip',value:0});assert.equal(p.damageSkinId,0);send({action:'damageEquip',value:2});assert.equal(p.damageSkinId,2);});
test('cash skin purchases deduct confirmed currency once and cannot use gold',()=>{const {w,p}=setup();p.gold=100000;cashInput(w,p,{action:'cashBuy',value:7},now);cashInput(w,p,{action:'cashEquip',value:9},now);assert.equal(p.damageSkinId,0);p.cash=750;for(const id of [7,8,9]){cashInput(w,p,{action:'cashBuy',value:id},now);const cash:number=p.cash||0;cashInput(w,p,{action:'cashBuy',value:id},now);assert.equal(p.cash,cash);}assert.equal(p.cash,0);assert.deepEqual(p.damageSkins,[3,4,5]);cashInput(w,p,{action:'cashEquip',value:7},now);assert.equal(p.damageSkinId,3);assert.equal(p.gold,100000);});
test('cosmetics preserve stats and actual damage; tutorial and ownership survive serialization',()=>{const {w,p}=setup();p.damageSkins=[5];p.damageSkinId=5;const before=stats(p),m=w.monsters.find(m=>m.zone===1)!;m.hp=999;damageMonster(w,m,p,10,now);assert.equal(w.events.at(-1)?.damageSkinId,5);assert.equal(m.hp,983);assert.deepEqual(stats(p),before);p.tutorial!.moved=80;const restored=JSON.parse(JSON.stringify(w));assert.equal(restored.players[p.id].damageSkinId,5);assert.equal(restored.players[p.id].tutorial.moved,80);});
