import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,newPlayer,applyInput,tickWorld} from '../server/engine';
import {accountFor,changeAccount,ownedPlayer,roster} from '../shared/accounts';
import {findPath} from '../shared/navigation';
import {clearSight} from '../shared/physics';
import {PositionBuffer} from '../components/game/interpolation';
const time=1800000000000;
test('guest migration preserves the existing character; accounts cannot select or delete others',()=>{const w=createWorld(time);w.players.old=newPlayer('old','기존수호자',0,time);const a=accountFor(w,'old');assert.deepEqual(a.characters,['old']);assert.equal(ownedPlayer(w,'other','old'),undefined);assert.throws(()=>changeAccount(w,'other',{action:'select',characterId:'old'},time));assert.throws(()=>changeAccount(w,'other',{action:'delete',characterId:'old'},time));assert.ok(w.players.old);});
test('four slots enforced and additional slots cost server-owned gold exactly once',()=>{const w=createWorld(time);for(let i=0;i<4;i++)changeAccount(w,'owner',{action:'create',name:'수호자'+i,classId:i%3},time);assert.equal(roster(w,'owner').characters.length,4);assert.throws(()=>changeAccount(w,'owner',{action:'create',name:'초과',classId:0},time));assert.throws(()=>changeAccount(w,'owner',{action:'buySlot'},time));const p=ownedPlayer(w,'owner')!;p.gold=5000;changeAccount(w,'owner',{action:'buySlot'},time);assert.equal(p.gold,0);assert.equal(roster(w,'owner').slots,5);assert.throws(()=>changeAccount(w,'owner',{action:'buySlot'},time));changeAccount(w,'owner',{action:'create',name:'다섯째',classId:2},time);assert.equal(roster(w,'owner').characters.length,5);});
test('delete frees a slot and preserves other character progress',()=>{const w=createWorld(time);changeAccount(w,'owner',{action:'create',name:'첫째',classId:0},time);const first=ownedPlayer(w,'owner')!;first.level=15;changeAccount(w,'owner',{action:'create',name:'둘째',classId:1},time);const second=ownedPlayer(w,'owner')!;changeAccount(w,'owner',{action:'delete',characterId:second.id},time);assert.equal(w.players[second.id],undefined);assert.equal(ownedPlayer(w,'owner')?.level,15);});
test('quest pathfinding returns a traversable route from spawn to Sera',()=>{const start={x:900,y:830},path=findPath(start,{x:830,y:645},0);assert.ok(path.length);let a=start;for(const b of path){assert.ok(clearSight({...a,zone:0},b));a=b;}});
test('buffer interpolates uneven snapshots, does not extrapolate stops, resets teleports',()=>{const b=new PositionBuffer();b.add(1000,0,0);b.add(1100,10,0);b.add(1300,30,0);assert.equal(b.at(1200)?.x,20);assert.equal(b.at(2000)?.x,30);assert.equal(b.at(2000)?.moving,false);b.add(1400,1000,500);assert.equal(b.at(1250)?.x,1000);});

test('voice mapping covers class-specific attack and reaction actions',async()=>{const {voiceClip}=await import('../shared/voice');assert.equal(voiceClip(2,'attack',1),'fire');assert.equal(voiceClip(2,'attack',2),'freeze');assert.equal(voiceClip(0,'attack',2),'cyclone');assert.equal(voiceClip(1,'dodge',0,2),'jump3');assert.equal(voiceClip(0,'hurt',0,1),'damaged2');});

import {socialInput,tradeFor,expireTrades} from '../server/social';
import {enterRaid,tickRaids} from '../server/raids';
import {damageMonster} from '../server/combat';
import {BUBBLES,RAIDS} from '../shared/social';
function pair(){const w=createWorld(time),a=newPlayer('a','첫째',0,time),b=newPlayer('b','둘째',1,time);w.players={a,b};a.inventory=[0,3,7,8];b.inventory=[1,3,9,10];a.gold=b.gold=1000;return {w,a,b};}
function trading(){const r=pair();socialInput(r.w,r.a,{action:'tradeRequest',targetId:r.b.id},time);const t=tradeFor(r.w,r.a.id)!;socialInput(r.w,r.b,{action:'tradeAccept',tradeId:t.id},time);return {...r,t};}
test('bubble catalog contains 12 styles; purchases charge once, equip requires ownership',()=>{const {w,a}=pair();assert.equal(BUBBLES.filter(b=>!b.cashOnly).length,12);socialInput(w,a,{action:'bubbleEquip',value:11},time);assert.equal(a.bubbleId,undefined);socialInput(w,a,{action:'bubbleBuy',value:1},time);assert.equal(a.gold,880);socialInput(w,a,{action:'bubbleBuy',value:1},time);assert.equal(a.gold,880);assert.equal(a.bubbleId,1);});
test('trade transfers both inventories and gold once after mutual confirmation',()=>{const {w,a,b,t}=trading();socialInput(w,a,{action:'tradeOffer',tradeId:t.id,indices:[2],gold:80},time);socialInput(w,b,{action:'tradeOffer',tradeId:t.id,indices:[2],gold:20},time);const confirm={action:'tradeConfirm',tradeId:t.id,revision:t.revision};socialInput(w,a,confirm,time);assert.equal(a.gold,1000);socialInput(w,b,confirm,time);assert.equal(a.gold,940);assert.equal(b.gold,1060);assert.deepEqual(a.inventory,[0,3,8,9]);assert.deepEqual(b.inventory,[1,3,10,7]);socialInput(w,b,confirm,time);assert.equal(b.gold,1060);assert.equal(tradeFor(w,a.id),undefined);});
test('trade rejects third parties, equipped items, duplicate indices and negative gold',()=>{const {w,a,b,t}=trading();const c=newPlayer('c','침입',0,time);w.players.c=c;socialInput(w,c,{action:'tradeCancel',tradeId:t.id},time);assert.ok(tradeFor(w,a.id));for(const offer of [{indices:[0],gold:0},{indices:[2,2],gold:0},{indices:[2],gold:-1},{indices:[99],gold:0}])socialInput(w,a,{action:'tradeOffer',tradeId:t.id,...offer},time);assert.deepEqual(t.offers.a.items,[]);socialInput(w,a,{action:'tradeCancel',tradeId:t.id},time);assert.equal(a.gold,1000);assert.equal(b.gold,1000);});
test('changing offer resets confirmations; stale revision cannot finalize',()=>{const {w,a,b,t}=trading();socialInput(w,a,{action:'tradeOffer',tradeId:t.id,indices:[2],gold:20},time);const old=t.revision;socialInput(w,a,{action:'tradeConfirm',tradeId:t.id,revision:old},time);socialInput(w,b,{action:'tradeOffer',tradeId:t.id,indices:[2],gold:10},time);assert.equal(t.offers.a.confirmed,false);socialInput(w,a,{action:'tradeConfirm',tradeId:t.id,revision:old},time);assert.equal(t.offers.a.confirmed,false);});
test('inventory changes, insufficient funds and full bag prevent partial trade transfers',()=>{for(const change of ['inventory','gold','capacity']){const {w,a,b,t}=trading();socialInput(w,a,{action:'tradeOffer',tradeId:t.id,indices:[2],gold:50},time);socialInput(w,b,{action:'tradeOffer',tradeId:t.id,indices:[],gold:0},time);if(change==='inventory')a.inventory[2]=10;if(change==='gold')a.gold=0;if(change==='capacity')b.inventory=Array(60).fill(9);const ag=a.gold,bg=b.gold;socialInput(w,a,{action:'tradeConfirm',tradeId:t.id,revision:t.revision},time);socialInput(w,b,{action:'tradeConfirm',tradeId:t.id,revision:t.revision},time);assert.equal(a.gold,ag);assert.equal(b.gold,bg);assert.ok(tradeFor(w,a.id));}});
test('distance and offline expiry cancel trades without losing assets',()=>{const {w,a,b}=trading();b.x+=300;expireTrades(w,time);assert.equal(tradeFor(w,a.id),undefined);assert.equal(a.gold,1000);const r=trading();expireTrades(r.w,time+16000);assert.equal(r.w.trades?.length,0);});
test('raid level gates, dedicated maps and maximum four participants',()=>{const {w,a}=pair();enterRaid(w,a,0,time);assert.equal(a.zone,0);a.level=10;enterRaid(w,a,0,time);assert.equal(a.zone,25);assert.equal(w.monsters.filter(m=>m.zone===25).length,1);for(let n=0;n<4;n++){const p=newPlayer('raid'+n,'동료'+n,0,time);p.level=10;w.players[p.id]=p;enterRaid(w,p,0,time);assert.equal(p.zone,n===3?0:25);}assert.equal(w.raids?.[0].participants.length,4);});
test('raid rewards active contributors once and preserves full bag reward',()=>{const {w,a,b}=pair();a.level=b.level=10;enterRaid(w,a,0,time);enterRaid(w,b,0,time);a.inventory=Array(60).fill(7);const boss=w.monsters.find(m=>m.zone===25)!;const gold=a.gold;damageMonster(w,boss,a,boss.hp,time);assert.equal(a.gold,gold+RAIDS[0].gold);assert.deepEqual(a.raidRewards,[14]);assert.equal(b.gold,1000,'non-contributor does not receive reward');damageMonster(w,boss,a,999999,time);assert.equal(a.gold,gold+RAIDS[0].gold);assert.equal(w.raids?.[0].status,'won');tickWorld(w,time+100000);assert.equal(boss.hp,0,'defeated raid boss never regular-respawns');a.inventory.pop();applyInput(w,a,{seq:1,action:'raidClaim'},time+100001);assert.equal(a.inventory.at(-1),14);assert.equal(a.raidRewards.length,0);});
test('raid deadline and party defeat end battle; general travel cannot bypass level gate',()=>{const {w,a}=pair();a.level=10;applyInput(w,a,{seq:1,action:'travel',value:25},time+100);assert.equal(a.zone,0);enterRaid(w,a,0,time);tickRaids(w,time+RAIDS[0].minutes*60000);assert.equal(w.raids?.[0].status,'failed');const r=pair();r.a.level=10;enterRaid(r.w,r.a,0,time);r.a.hp=0;r.a.seen=time+20000;tickRaids(r.w,time+20000);assert.equal(r.w.raids?.[0].status,'failed');});
test('re-entering an active raid cannot reset HP/MP or evade the party cap',()=>{const {w,a}=pair();a.level=10;enterRaid(w,a,0,time);a.hp=10;a.mp=4;enterRaid(w,a,0,time+100);assert.equal(a.hp,10);assert.equal(a.mp,4);assert.equal(w.raids?.length,1);assert.equal(w.raids?.[0].participants.length,1);});

import {SnapshotTimeline} from '../components/game/interpolation';
test('short packet gaps predict with decaying velocity, never overshoot indefinitely or flip stationary facing',()=>{
 const b=new PositionBuffer();b.add(1000,40,0);b.add(1100,30,0);
 const late=b.at(1200,180)!;assert.ok(late.x<30&&late.x>20);assert.equal(late.face,-1);assert.equal(late.moving,true);
 const stopped=b.at(4000,180)!;assert.ok(stopped.x>=21&&stopped.x<30);assert.equal(stopped.moving,false);assert.equal(b.at(5000,180)!.x,stopped.x);
 b.add(1200,30,0);assert.equal(b.at(1250,180)!.x,30);assert.equal(b.at(1250,180)!.face,-1);
 b.add(1300,900,700);assert.equal(b.at(1200,180)!.x,900);
});
test('network playback stays monotonic across delayed packets and adjusts to slower arrivals',()=>{
 const clock=new SnapshotTimeline();clock.add(1000,1100);let last=clock.at(1100);const initial=clock.delay;
 for(let frame=1116;frame<1800;frame+=16){if(frame===1420)clock.add(1200,frame);const next=clock.at(frame);assert.ok(next>=last);assert.ok(next-last<=20);last=next;}
 assert.ok(clock.delay>initial);clock.add(1100,1900);assert.ok(clock.at(1900)>=last,'out-of-order packets cannot rewind playback');
});

test('playback catches up immediately after a suspended mobile tab',()=>{const clock=new SnapshotTimeline();clock.add(1000,1100);clock.at(1100);clock.add(31000,31100);assert.ok(clock.at(31100)>30000);});
