import {hurtPlayer} from '../server/combat';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newPlayer,createWorld,applyInput,tickWorld,needXp,stats,addXp,movable,snapshot} from '../server/engine';
import {NPCS,ITEMS,QUESTS,MONSTERS,WORLD} from '../shared/content';
const initial=1_800_000_000_000;
const setup=()=>{const w=createWorld(initial),p=newPlayer('test','테스터',0,initial);w.players[p.id]=p;return {w,p};};
test('network retries cannot shorten the movement allowed for the next fresh input',()=>{
 const a=setup(),b=setup();
 for(const state of [a,b])applyInput(state.w,state.p,{seq:1,dx:1,moveX:10,moveY:0},initial+100);
 const before=a.p.x;
 applyInput(a.w,a.p,{seq:1,dx:1,moveX:10,moveY:0},initial+190);
 assert.equal(a.p.x,before,'duplicate input cannot move the character twice');
 for(const state of [a,b])applyInput(state.w,state.p,{seq:2,dx:1,moveX:WORLD.speed*.2,moveY:0},initial+300);
 assert.equal(a.p.x,b.p.x,'retried and clean connections retain the same allowed movement');
});
test('equipment modifies stats; unowned equipment cannot be equipped',()=>{const {w,p}=setup();const base=stats(p);applyInput(w,p,{seq:1,action:'equip',value:14},initial+1000);assert.equal(p.equipment.weapon,0);p.inventory.push(14);applyInput(w,p,{seq:2,action:'equip',value:14},initial+1200);assert.equal(p.equipment.weapon,14);assert.ok(stats(p).atk>base.atk);});
test('movement normalized, bounded and never trusts absolute coordinates',()=>{const {w,p}=setup();const x=p.x,y=p.y;applyInput(w,p,{seq:1,dx:10000,dy:10000},initial+1000);assert.ok(Math.hypot(p.x-x,p.y-y)<=WORLD.speed*.5+.001);p.x=180;p.y=700;applyInput(w,p,{seq:2,dx:-1},initial+1500);assert.ok(p.x>180);assert.ok(movable(p.x,p.y));assert.equal(movable(1150,250),false);});
test('server calculates damage, awards XP, creates loot; cooldown and duplicates enforced',()=>{const {w,p}=setup();p.zone=1;p.x=510;p.y=410;const m=w.monsters.find(m=>m.zone===1)!;m.hp=1;const input={seq:1,skill:0,tx:m.x,ty:m.y};applyInput(w,p,input,initial+1000);assert.equal(m.hp,0);assert.ok(p.xp>0);assert.equal(w.loot.length,1);const kills={...p.kills};applyInput(w,p,input,initial+1100);assert.deepEqual(p.kills,kills);assert.equal(w.loot.length,1);const next=w.monsters.find(m=>m.zone===1&&m.hp>0)!;next.x=p.x+20;next.y=p.y;const hp=next.hp;applyInput(w,p,{seq:2,skill:0,tx:next.x,ty:next.y},initial+1200);assert.equal(next.hp,hp);});
test('MP consumption and cooldown validation',()=>{const {w,p}=setup();p.zone=1;p.mp=0;applyInput(w,p,{seq:1,skill:3},initial+1000);assert.equal(p.cd[3],0);p.mp=80;applyInput(w,p,{seq:2,skill:3},initial+1200);assert.equal(p.mp,55);const cd=p.cd[3];applyInput(w,p,{seq:3,skill:3},initial+1300);assert.equal(p.mp,55);assert.equal(p.cd[3],cd);});
test('EXP handles multiple level-ups and full restoration',()=>{const {p}=setup();p.hp=1;p.mp=0;const xp=needXp(1)+needXp(2)+15;assert.equal(addXp(p,xp),true);assert.equal(p.level,3);assert.equal(p.xp,15);assert.equal(p.hp,stats(p).hp);assert.equal(p.mp,stats(p).mp);});
test('loot ownership, gold, potion and equipment inventory',()=>{const {w,p}=setup();w.loot.push({id:'l',owner:p.id,zone:0,x:p.x,y:p.y,gold:12,item:7,potion:true,expires:initial+60000});const gold=p.gold,potions=p.potions;applyInput(w,p,{seq:1,action:'loot'},initial+1000);assert.equal(p.gold,gold+12);assert.ok(p.inventory.includes(7));assert.equal(p.potions,potions+1);assert.equal(w.loot.length,0);w.loot.push({id:'foreign',owner:'other',zone:0,x:p.x,y:p.y,gold:100,item:0,potion:false,expires:initial+60000});applyInput(w,p,{seq:2,action:'loot'},initial+1200);assert.equal(w.loot.length,1);});
test('quest accept, kill progress, reward exactly once',()=>{const {w,p}=setup();p.x=830;p.y=560;applyInput(w,p,{seq:1,action:'quest',value:0},initial+1000);assert.equal(p.quests[0],0);p.quests[0]=QUESTS[0].count;const gold=p.gold;applyInput(w,p,{seq:2,action:'quest',value:0},initial+1500);assert.equal(p.gold,gold+QUESTS[0].gold);assert.ok(p.done.includes(0));applyInput(w,p,{seq:3,action:'quest',value:0},initial+2000);assert.equal(p.gold,gold+QUESTS[0].gold);});
test('shop transaction requires distance and cannot spend more than owned',()=>{const {w,p}=setup();p.x=400;p.y=400;applyInput(w,p,{seq:1,action:'buy',value:-1},initial+1000);assert.equal(p.potions,8);p.x=1030;p.y=600;applyInput(w,p,{seq:2,action:'buy',value:-1},initial+1200);assert.equal(p.potions,11);assert.equal(p.gold,62);applyInput(w,p,{seq:3,action:'buy',value:14},initial+1500);assert.equal(p.gold,62);assert.ok(!p.inventory.includes(14));});
test('portal proximity, zone changes and respawn',()=>{const {w,p}=setup();applyInput(w,p,{seq:1,action:'portal',value:0},initial+1000);assert.equal(p.zone,0);p.x=1530;p.y=680;applyInput(w,p,{seq:2,action:'portal',value:0},initial+1200);assert.equal(p.zone,1);assert.equal(p.x,400);p.hp=0;applyInput(w,p,{seq:3,skill:0},initial+1500);assert.equal(p.hp,0);applyInput(w,p,{seq:4,action:'respawn'},initial+1800);assert.equal(p.zone,0);assert.equal(p.hp,stats(p).hp);});
test('20 online players share monster state, presence and server simulation',()=>{const w=createWorld(initial);for(let i=0;i<20;i++){const p=newPlayer('p'+i,'수호자'+i,i%3,initial);p.zone=1;p.x=510+i*3;p.y=430;w.players[p.id]=p;}tickWorld(w,initial+500);const p=w.players.p0;applyInput(w,p,{seq:1,skill:1,tx:500,ty:400},initial+600);const a=snapshot(w,p,initial+600),b=snapshot(w,w.players.p1,initial+600);assert.equal(a.online,20);assert.equal(a.players.length,19);assert.deepEqual(a.monsters,b.monsters);assert.ok(a.monsters.some(m=>m.hp<m.maxHp));});
test('dead monsters respawn; inactive players not targeted',()=>{const {w,p}=setup();const m=w.monsters[0];m.hp=0;m.deadUntil=initial+1000;tickWorld(w,initial+1500);assert.equal(m.hp,MONSTERS[m.type].hp);p.zone=1;p.x=m.x;p.y=m.y;p.seen=initial-20000;const hp=p.hp;tickWorld(w,initial+2000);assert.equal(p.hp,hp);});
test('data includes 3 classes, 25 zones, 23 monsters, 47 equipment and 125 quests',()=>{assert.equal(ITEMS.length,47);assert.equal(QUESTS.length,125);assert.equal(MONSTERS.length,23);assert.ok(createWorld(initial).monsters.some(m=>m.type===9));});

test('dodge is server-controlled, collision-safe and has cooldown/invulnerability',()=>{const {w,p}=setup();p.zone=1;p.x=1000;p.y=600;const hp=p.hp;applyInput(w,p,{seq:1,action:'dodge',tx:1400,ty:600},initial+1000);assert.equal(p.x,1150);assert.ok((p.dodgeUntil||0)>initial+1000);hurtPlayer(w,p,40,initial+1200);assert.equal(p.hp,hp);const x=p.x;applyInput(w,p,{seq:2,action:'dodge',tx:1400,ty:600},initial+1200);assert.equal(p.x,x);p.dodgeCd=0;p.x=1020;p.y=270;applyInput(w,p,{seq:3,action:'dodge',tx:1400,ty:270},initial+1500);assert.ok(p.x<1080);assert.ok(movable(p.x,p.y));assert.equal(p.hp,hp);hurtPlayer(w,p,40,initial+1900);assert.ok(p.hp<hp);});
test('knight combo advances and heavy strike applies server stun',()=>{const {w,p}=setup();p.zone=1;p.x=700;p.y=600;const m=w.monsters[0];w.monsters=[m];m.x=770;m.y=600;m.hp=1000;m.maxHp=1000;for(let i=1;i<=3;i++)applyInput(w,p,{seq:i,skill:0,tx:900,ty:600},initial+i*800);assert.equal(p.combo,3);assert.ok(w.events.some(e=>e.kind==='spell'&&e.value===3));applyInput(w,p,{seq:4,skill:1,tx:900,ty:600},initial+3300);assert.ok((m.stunUntil||0)>initial+3300);});
test('ranger piercing shot hits a line and excludes off-axis monsters',()=>{const w=createWorld(initial),p=newPlayer('ranger','순찰자',1,initial);w.players[p.id]=p;p.zone=1;p.x=700;p.y=600;w.monsters=w.monsters.slice(0,3);w.monsters.forEach((m,i)=>{m.zone=1;m.hp=500;m.maxHp=500;m.x=780+i*70;m.y=i===2?730:600;});applyInput(w,p,{seq:1,skill:2,tx:1200,ty:600},initial+1000);assert.ok(w.monsters[0].hp<500);assert.ok(w.monsters[1].hp<500);assert.equal(w.monsters[2].hp,500);});
test('mage frost halts movement and fireball deals repeated burn damage',()=>{const w=createWorld(initial),p=newPlayer('mage','마도사',2,initial);w.players[p.id]=p;p.zone=1;p.x=700;p.y=600;w.monsters=w.monsters.slice(0,1);const m=w.monsters[0];m.zone=1;m.x=780;m.y=600;m.hp=500;m.maxHp=500;applyInput(w,p,{seq:1,skill:2,tx:780,ty:600},initial+1000);assert.ok((m.freezeUntil||0)>initial+1000);const x=m.x;tickWorld(w,initial+1300);assert.equal(m.x,x);applyInput(w,p,{seq:2,skill:1,tx:m.x,ty:m.y},initial+1600);assert.ok((m.burnUntil||0)>initial+1600);const hp=m.hp;tickWorld(w,initial+2300);assert.ok(m.hp<hp);});
test('meteor is delayed, bounded, persistent and resolves an area attack',()=>{const w=createWorld(initial),p=newPlayer('mage','마도사',2,initial);w.players[p.id]=p;p.zone=1;p.x=700;p.y=600;w.monsters=w.monsters.slice(0,2);for(const m of w.monsters){m.zone=1;m.hp=500;m.maxHp=500;m.x=850;m.y=600;}applyInput(w,p,{seq:1,skill:3,tx:850,ty:600},initial+1000);assert.equal(w.casts?.length,1);assert.equal(w.monsters[0].hp,500);const restored=JSON.parse(JSON.stringify(w));tickWorld(restored,initial+1800);assert.equal(restored.casts.length,0);assert.ok(restored.monsters.every((m:{hp:number})=>m.hp<500));});
test('skill upgrades spend earned points exactly once and cap at rank 3',()=>{const {w,p}=setup();p.level=4;for(let i=1;i<=3;i++)applyInput(w,p,{seq:i,action:'train',value:0},initial+i*500);assert.equal(p.skillRanks?.[0],3);applyInput(w,p,{seq:4,action:'train',value:0},initial+2200);assert.equal(p.skillRanks?.[0],3);applyInput(w,p,{seq:5,action:'train',value:1},initial+2500);assert.equal(p.skillRanks?.[1],0);});
test('potions do not waste charges at full HP and cannot be spammed',()=>{const {w,p}=setup();applyInput(w,p,{seq:1,action:'potion'},initial+1000);assert.equal(p.potions,8);p.hp=20;applyInput(w,p,{seq:2,action:'potion'},initial+1200);assert.equal(p.potions,7);assert.equal(p.hp,100);applyInput(w,p,{seq:3,action:'potion'},initial+1500);assert.equal(p.potions,7);assert.equal(p.hp,100);});
test('boss telegraphs its slam; moving out of the circle prevents damage',()=>{const {w,p}=setup();p.zone=4;p.x=900;p.y=600;w.monsters=w.monsters.filter(m=>m.zone===4&&m.type===9).slice(0,1);const m=w.monsters[0];m.x=700;m.y=600;m.nextSpecial=0;const hp=p.hp;tickWorld(w,initial+1000);assert.equal(p.hp,hp);assert.equal(m.attackX,900);assert.ok((m.attackUntil||0)>initial+1000);p.x=1250;p.y=600;p.seen=initial+2000;tickWorld(w,initial+2300);assert.equal(p.hp,hp);assert.equal(m.attackUntil,0);});

test('image-map travel works from any location and enforces level gates',()=>{const {w,p}=setup();p.x=900;p.y=925;applyInput(w,p,{seq:1,action:'travel',value:24},initial+1000);assert.equal(p.zone,0);assert.match(p.notice,/49/);p.level=49;applyInput(w,p,{seq:2,action:'travel',value:24},initial+1200);assert.equal(p.zone,24);assert.equal(p.x,900);assert.equal(p.y,830);p.x=500;p.y=500;applyInput(w,p,{seq:3,action:'travel',value:0},initial+1600);assert.equal(p.zone,0);});
test('advanced skills require level and a spent point, then loadout can assign and remove',()=>{const {w,p}=setup();p.zone=1;p.x=700;p.y=600;applyInput(w,p,{seq:1,action:'bind',slot:0,value:4},initial+1000);assert.equal(p.loadout?.[0],0);p.level=5;applyInput(w,p,{seq:2,skill:4},initial+1200);assert.equal(p.cd[4],undefined);applyInput(w,p,{seq:3,action:'train',value:4},initial+1600);assert.equal(p.skillRanks?.[4],1);applyInput(w,p,{seq:4,action:'bind',slot:0,value:4},initial+1800);assert.equal(p.loadout?.[0],4);applyInput(w,p,{seq:5,skill:4},initial+2000);assert.ok(p.cd[4]>initial+2000);applyInput(w,p,{seq:6,action:'bind',slot:0,value:-1},initial+2400);assert.equal(p.loadout?.[0],-1);applyInput(w,p,{seq:7,action:'bind',slot:8,value:7},initial+2800);assert.equal(p.loadout?.length,4);});
test('movement deltas catch up after latency while enforcing speed and terrain walls',()=>{const {w,p}=setup();p.x=700;p.y=600;applyInput(w,p,{seq:1,moveX:105,moveY:0},initial+500);assert.ok(Math.abs(p.x-805)<.001);applyInput(w,p,{seq:2,moveX:10000,moveY:0},initial+600);assert.ok(p.x<=828.01);p.x=1000;p.y=600;applyInput(w,p,{seq:3,moveX:420,moveY:0},initial+2600);assert.ok(p.x<=1420);p.x=900;p.y=450;applyInput(w,p,{seq:4,moveX:0,moveY:-1000},initial+4600);assert.ok(p.y>140);assert.ok(movable(p.x,p.y));});
test('all painted biome walls stop walk and dodge without blocking their travel orb',()=>{const {w,p}=setup();for(const zone of [0,10,16]){p.zone=zone;p.x=900;p.y=925;assert.ok(movable(p.x,p.y,zone));p.x=900;p.y=800;applyInput(w,p,{seq:zone+1,moveX:0,moveY:500},initial+10000+zone*1000);assert.ok(p.y<1020);assert.equal(movable(1500,100,zone),false);}});
test('regional quest progress only counts monsters in its assigned map',()=>{const {w,p}=setup();p.quests[5]=0;p.zone=6;p.level=10;p.x=700;p.y=600;const m=w.monsters.find(m=>m.type===8&&m.zone===6)!;w.monsters=[m];m.x=740;m.y=600;m.hp=1;applyInput(w,p,{seq:1,skill:0,tx:m.x,ty:m.y},initial+1000);assert.equal(p.quests[5],0);p.zone=5;m.zone=5;m.hp=1;p.cd[0]=0;applyInput(w,p,{seq:2,skill:0,tx:m.x,ty:m.y},initial+2000);assert.equal(p.quests[5],1);});

test('click promotion upgrades immediately at required level, clears old trials and rejects replay or locked tiers',()=>{const {w,p}=setup();p.zone=1;p.x=700;p.y=600;p.level=19;applyInput(w,p,{seq:1,action:'promotion'},initial+1000);assert.equal(p.promotionTier,undefined);p.level=20;p.promotionQuest={tier:1,kills:0,bosses:0};const before=stats(p);applyInput(w,p,{seq:2,action:'promotion'},initial+2000);assert.equal(p.promotionTier,1);assert.equal(p.promotionQuest,undefined);assert.ok(stats(p).atk>before.atk);assert.equal(p.hp,stats(p).hp);applyInput(w,p,{seq:2,action:'promotion'},initial+2100);assert.equal(p.promotionTier,1);applyInput(w,p,{seq:3,action:'promotion'},initial+2200);assert.equal(p.promotionTier,1);p.level=30;applyInput(w,p,{seq:4,action:'promotion'},initial+3000);assert.equal(p.promotionTier,2);applyInput(w,p,{seq:5,action:'promotion'},initial+4000);assert.equal(p.promotionTier,2);assert.equal(p.promotionQuest,undefined);});
test('growth curve slows early and late progression while preserving existing levels',()=>{assert.ok(needXp(1)>=180);assert.ok(needXp(10)>70*10**1.45*3);const {p}=setup();p.level=20;p.xp=100;addXp(p,0);assert.equal(p.level,20);assert.equal(p.xp,100);});

test('idle monsters move continuously without overshooting home targets',()=>{const w=createWorld(initial),m=w.monsters.find(m=>m.zone===1)!;m.x=900;m.y=700;m.homeX=850;m.homeY=700;w.monsters=[m];for(let i=1;i<240;i++){const x=m.x,y=m.y;tickWorld(w,initial+i*50);assert.ok(Math.hypot(m.x-x,m.y-y)<=35*.05+.001);assert.ok(movable(m.x,m.y,m.zone));}});

test('pet purchase requires merchant proximity, sufficient gold and rejects duplicate charges',()=>{const {w,p}=setup();p.x=600;p.y=400;p.gold=2000;applyInput(w,p,{seq:1,action:'buyPet',value:0},initial+1000);assert.equal(p.pets,undefined);p.x=1030;p.y=600;applyInput(w,p,{seq:2,action:'buyPet',value:0},initial+1300);assert.deepEqual(p.pets,[0]);assert.equal(p.gold,1500);assert.equal(p.petId,0);applyInput(w,p,{seq:3,action:'buyPet',value:0},initial+1500);assert.equal(p.gold,1500);applyInput(w,p,{seq:4,action:'equipPet',value:2},initial+1700);assert.equal(p.petId,0);});
test('equipped pets collect nearby owned loot once, respect foreign ownership and can be disabled',()=>{const {w,p}=setup();p.pets=[0];p.petId=0;const gold=p.gold;w.loot=[{id:'own',owner:p.id,zone:0,x:p.x+20,y:p.y,gold:30,item:7,potion:true,expires:initial+60000},{id:'foreign',owner:'other',zone:0,x:p.x+30,y:p.y,gold:100,item:null,potion:false,expires:initial+60000}];tickWorld(w,initial+1000);assert.equal(p.gold,gold+30);assert.ok(p.inventory.includes(7));assert.equal(w.loot.length,1);tickWorld(w,initial+1600);assert.equal(p.gold,gold+30);p.petAutoLoot=false;w.loot.push({id:'disabled',owner:p.id,zone:0,x:p.x,y:p.y,gold:10,item:null,potion:false,expires:initial+60000});tickWorld(w,initial+2200);assert.equal(p.gold,gold+30);});
test('full inventory keeps equipment on the ground while collecting gold only once',()=>{const {w,p}=setup();p.inventory=Array(60).fill(0);w.loot=[{id:'full',owner:p.id,zone:0,x:p.x,y:p.y,gold:25,item:7,potion:false,expires:initial+60000}];const gold=p.gold;applyInput(w,p,{seq:1,action:'loot'},initial+1000);assert.equal(p.gold,gold+25);assert.equal(w.loot[0].item,7);assert.equal(w.loot[0].gold,0);applyInput(w,p,{seq:2,action:'loot'},initial+1200);assert.equal(p.gold,gold+25);p.inventory.pop();applyInput(w,p,{seq:3,action:'loot'},initial+1500);assert.equal(w.loot.length,0);assert.ok(p.inventory.includes(7));});

// v12 automatic training and new equipment follow the same authoritative rules.
test('automatic training respects earned points, caps and promotion gates, then resumes on level up',()=>{const {w,p}=setup();p.level=10;applyInput(w,p,{seq:1,action:'autoSkillMode',value:3},initial+1000);assert.equal(p.autoSkillMode,3);assert.equal(p.skillRanks!.reduce((a,b)=>a+b,0),9);assert.equal(p.skillRanks![8],0);assert.ok(p.skillRanks!.every(n=>n<=3));const before=[...p.skillRanks!];applyInput(w,p,{seq:1,action:'autoSkillMode',value:3},initial+1100);assert.deepEqual(p.skillRanks,before);addXp(p,100000);assert.ok(p.skillRanks!.reduce((a,b)=>a+b,0)>9);assert.equal(p.skillRanks![8],0);p.promotionTier=1;tickWorld(w,initial+1300);assert.ok(p.skillRanks![8]>0);applyInput(w,p,{seq:2,action:'autoSkillMode',value:0},initial+1400);assert.equal(p.autoSkillMode,0);});
test('automatic hotbar training prioritizes equipped skills and retains excess points',()=>{const {w,p}=setup();p.level=8;p.loadout=[2,3,-1,-1];applyInput(w,p,{seq:1,action:'autoSkillMode',value:2},initial+1000);assert.equal(p.skillRanks![2],3);assert.equal(p.skillRanks![3],3);p.level=50;p.promotionTier=2;tickWorld(w,initial+1200);assert.equal(p.skillRanks!.reduce((a,b)=>a+b,0),36);assert.ok(p.skillRanks!.every(n=>n===3));applyInput(w,p,{seq:2,action:'autoSkillMode',value:99},initial+1300);assert.equal(p.autoSkillMode,2);});
test('new equipment purchase enforces level and equip enforces class without losing gold',()=>{const {w,p}=setup();const shop=NPCS.find(n=>n.zone===0&&n.service==='shop')!;p.x=shop.x;p.y=shop.y;p.gold=99999;const gold=p.gold;applyInput(w,p,{seq:1,action:'buy',value:21},initial+1000);assert.equal(p.gold,gold);assert.ok(!p.inventory.includes(21));p.level=8;applyInput(w,p,{seq:2,action:'buy',value:21},initial+1200);assert.ok(p.inventory.includes(21));applyInput(w,p,{seq:3,action:'equip',value:21},initial+1300);assert.equal(p.equipment.weapon,21);p.inventory.push(22);applyInput(w,p,{seq:4,action:'equip',value:22},initial+1400);assert.equal(p.equipment.weapon,21);assert.ok(ITEMS.slice(21).every((i,n)=>i.id===21+n));});
