import {test} from 'node:test';import assert from 'node:assert/strict';
import {createWorld,newPlayer,applyInput,migrateWorld,snapshot} from '../server/engine';
import {ITEMS,ZONES} from '../shared/content';import {GM_SKINS,GM_TITLES} from '../shared/gm-content';
import {gmMutate} from '../server/gm';import {socialInput} from '../server/social';import {workshopInput} from '../server/workshop';
const now=1800000000000;function setup(){const w=createWorld(now),p=newPlayer('gm-test','수호자',0,now);w.players[p.id]=p;return {w,p};}
test('GM equipment cannot be bought by forged shop input, sold or salvaged',()=>{const {w,p}=setup(),id=ITEMS.find(i=>i.gmOnly)!.id;p.x=1030;p.y=600;p.gold=10000;const n=p.inventory.length;applyInput(w,p,{seq:1,action:'buy',value:id},now);assert.equal(p.inventory.length,n);assert.equal(p.gold,10000);gmMutate(w,{playerId:p.id,revision:0,action:'giveItem',itemId:id,quantity:1},now);applyInput(w,p,{seq:2,action:'sell',value:n},now);assert.equal(p.inventory[n],id);assert.equal(p.gold,10000);p.x=1290;p.y=660;workshopInput(w,p,{action:'salvage',value:n});assert.equal(p.inventory[n],id);assert.equal(p.materials,undefined);});
test('GM equipment cannot be offered in player trade',()=>{const {w,p}=setup(),b=newPlayer('b','동료',1,now);w.players.b=b;const id=ITEMS.find(i=>i.gmOnly)!.id;p.inventory.push(id);socialInput(w,p,{action:'tradeRequest',targetId:b.id},now);const t=w.trades![0];socialInput(w,b,{action:'tradeAccept',tradeId:t.id},now);socialInput(w,p,{action:'tradeOffer',tradeId:t.id,indices:[p.inventory.length-1],gold:0},now);assert.deepEqual(t.offers[p.id].items,[]);});
test('GM cosmetics are audited, reject invalid IDs atomically and appear in multiplayer snapshot',()=>{const {w,p}=setup();gmMutate(w,{playerId:p.id,revision:0,action:'setSkin',cosmeticId:GM_SKINS.length-1},now);gmMutate(w,{playerId:p.id,revision:1,action:'setTitle',cosmeticId:GM_TITLES.length-1},now);assert.equal(p.gmTitle,GM_TITLES.at(-1));const before=JSON.stringify(p);assert.throws(()=>gmMutate(w,{playerId:p.id,revision:2,action:'setSkin',cosmeticId:99},now));assert.equal(JSON.stringify(p),before);assert.equal(w.gmAudit?.length,2);const b=newPlayer('b','동료',1,now);w.players.b=b;assert.equal(snapshot(w,b,now).players[0].gmSkin,2);const saved=JSON.parse(JSON.stringify(w));assert.equal(saved.players[p.id].gmTitle,p.gmTitle);gmMutate(w,{playerId:p.id,revision:2,action:'setSkin',cosmeticId:-1},now);gmMutate(w,{playerId:p.id,revision:3,action:'setTitle',cosmeticId:-1},now);assert.equal(p.gmSkin,undefined);assert.equal(p.gmTitle,undefined);});
test('v13 migration adds all six species in matching biomes once while preserving progress',()=>{const {w,p}=setup();w.contentVersion=4;w.monsters=w.monsters.filter(m=>m.type<13);p.gold=12345;p.done=[0,1];const old=w.monsters[0];old.hp=10;migrateWorld(w,now);const count=w.monsters.length;migrateWorld(w,now+1);assert.equal(w.monsters.length,count);assert.equal(new Set(w.monsters.map(m=>m.id)).size,count);assert.equal(p.gold,12345);assert.deepEqual(p.done,[0,1]);assert.equal(old.hp,10);for(const z of ZONES.filter(z=>z.id>0&&!z.safe&&!z.raid))for(const type of z.types.filter(t=>t>=13))assert.ok(w.monsters.some(m=>m.zone===z.id&&m.type===type));for(let type=13;type<=18;type++)assert.ok(w.monsters.some(m=>m.type===type));});
test('fresh worlds contain every new monster assigned to each hunting map and none in safe maps',()=>{const {w}=setup();for(const z of ZONES){if(z.safe||z.id===0){assert.ok(!w.monsters.some(m=>m.zone===z.id));continue;}if(z.raid)continue;for(const type of z.types.filter(t=>t>=13))assert.ok(w.monsters.some(m=>m.zone===z.id&&m.type===type));}});
