import {test} from 'node:test';import assert from 'node:assert/strict';
import {createWorld,newPlayer,stats} from '../server/engine';import {needXp} from '../shared/progression';import {gmMutate,gmAuthorized,gmDetail} from '../server/gm';import {socialInput} from '../server/social';import {voicePath} from '../shared/voice';
const now=1800000000000;function setup(){const w=createWorld(now),p=newPlayer('gm-target','수호자',0,now);w.players[p.id]=p;return {w,p};}
test('GM requires a configured strong token; guest and forged tokens fail',async()=>{const token='a'.repeat(64);assert.equal(await gmAuthorized(null,token),false);assert.equal(await gmAuthorized('Bearer '+token,''),false);assert.equal(await gmAuthorized('Bearer '+token,'short'),false);assert.equal(await gmAuthorized('Bearer '+'b'.repeat(64),token),false);assert.equal(await gmAuthorized('Bearer '+token,token),true);});
test('GM atomically sets level, XP, money and potions with immutable audit snapshots',()=>{const {w,p}=setup();gmMutate(w,{playerId:p.id,revision:0,action:'set',level:20,xp:123,gold:777,potions:40,manaPotions:30,reason:'이벤트'},now);assert.equal(p.level,20);assert.equal(p.xp,123);assert.equal(p.gold,777);assert.equal(p.gmRevision,1);assert.equal(p.potions,40);assert.equal(w.gmAudit?.[0].reason,'이벤트');p.gold=999;assert.equal((w.gmAudit?.[0].after as {gold:number}).gold,777);});
test('GM invalid mixed mutation rolls back every field and emits no audit entry',()=>{const {w,p}=setup(),before=JSON.stringify(p);assert.throws(()=>gmMutate(w,{playerId:p.id,revision:0,action:'set',level:20,gold:-10},now));assert.equal(JSON.stringify(p),before);assert.equal(w.gmAudit,undefined);assert.throws(()=>gmMutate(w,{playerId:p.id,revision:0,action:'set',level:51},now));assert.throws(()=>gmMutate(w,{playerId:p.id,revision:0,action:'set',xp:needXp(1)},now));});
test('GM stale and repeated revisions cannot duplicate grants',()=>{const {w,p}=setup(),input={playerId:p.id,revision:0,action:'giveItem' as const,itemId:14,quantity:2};gmMutate(w,input,now);assert.throws(()=>gmMutate(w,input,now),/REVISION_CONFLICT/);assert.equal(p.inventory.filter(id=>id===14).length,2);assert.equal(w.gmAudit?.length,1);});
test('GM grants experience using normal progression and gold deductions cannot create debt',()=>{const {w,p}=setup();gmMutate(w,{playerId:p.id,revision:0,action:'addXp',amount:needXp(1)+10},now);assert.equal(p.level,2);assert.equal(p.xp,10);gmMutate(w,{playerId:p.id,revision:1,action:'addGold',amount:-30},now);assert.equal(p.gold,50);assert.throws(()=>gmMutate(w,{playerId:p.id,revision:2,action:'addGold',amount:-51},now));assert.equal(p.gold,50);});
test('GM respects item IDs, capacity, ownership and removes equipped last copies safely',()=>{const {w,p}=setup();assert.throws(()=>gmMutate(w,{playerId:p.id,revision:0,action:'giveItem',itemId:99,quantity:1},now));p.inventory=Array(60).fill(0);assert.throws(()=>gmMutate(w,{playerId:p.id,revision:0,action:'giveItem',itemId:14,quantity:1},now));p.inventory=[0,3];gmMutate(w,{playerId:p.id,revision:0,action:'removeItem',itemId:0,quantity:1},now);assert.equal(p.equipment.weapon,null);assert.deepEqual(p.inventory,[3]);assert.throws(()=>gmMutate(w,{playerId:p.id,revision:1,action:'removeItem',itemId:14,quantity:1},now));});
test('GM level reductions reset current XP and clamp HP/MP; heal, teleport, kick and ban persist',()=>{const {w,p}=setup();p.level=30;p.xp=100;p.hp=stats(p).hp;p.mp=stats(p).mp;gmMutate(w,{playerId:p.id,revision:0,action:'set',level:1},now);assert.equal(p.xp,0);assert.equal(p.hp,stats(p).hp);p.hp=0;gmMutate(w,{playerId:p.id,revision:1,action:'heal'},now);assert.equal(p.hp,stats(p).hp);p.zone=5;gmMutate(w,{playerId:p.id,revision:2,action:'town'},now);assert.equal(p.zone,0);gmMutate(w,{playerId:p.id,revision:3,action:'kick'},now);assert.equal(p.gmBlockedUntil,now+30000);gmMutate(w,{playerId:p.id,revision:4,action:'ban'},now);assert.equal(p.gmBanned,true);gmMutate(w,{playerId:p.id,revision:5,action:'unban'},now);assert.equal(p.gmBanned,false);assert.equal(p.gmBlockedUntil,0);});
test('GM mutation cancels trade without transferring assets',()=>{const {w,p}=setup(),b=newPlayer('other','동료',1,now);w.players[b.id]=b;socialInput(w,p,{action:'tradeRequest',targetId:b.id},now);assert.equal(w.trades?.length,1);gmMutate(w,{playerId:p.id,revision:0,action:'addGold',amount:20},now);assert.equal(w.trades?.length,0);assert.equal(b.gold,80);assert.equal(p.gold,100);});
test('male knight uses actual male recordings, while female characters retain their voice packs',()=>{assert.equal(voicePath(0,'attack',0,2),'/voices/male/attack2.mp3');assert.equal(voicePath(0,'attack',3,5),'/voices/male/attackbig5.mp3');assert.equal(voicePath(0,'hurt',0,7),'/voices/male/hurt7.mp3');assert.equal(voicePath(0,'level',0,1),'/voices/male/victory1.mp3');assert.match(voicePath(1,'attack'),/^\/voices\/type-2\//);assert.match(voicePath(2,'attack',1),/^\/voices\/type-3\/fire/);});

test('GM cash grants, deductions and direct balance edit are audited and cannot underflow',()=>{const w=createWorld(now),p=newPlayer('cash-gm','캐시검증',0,now);w.players[p.id]=p;const granted=gmMutate(w,{playerId:p.id,revision:0,action:'addCash',amount:500,reason:'이벤트 보상'},now);assert.equal(p.cash,500);assert.equal(granted.cash,500);gmMutate(w,{playerId:p.id,revision:1,action:'addCash',amount:-200},now+1);assert.equal(p.cash,300);assert.throws(()=>gmMutate(w,{playerId:p.id,revision:2,action:'addCash',amount:-301},now+2));assert.equal(p.cash,300);assert.equal(p.gmRevision,2);gmMutate(w,{playerId:p.id,revision:2,action:'set',cash:900},now+3);assert.equal(p.cash,900);assert.equal(w.gmAudit?.length,3);assert.equal((w.gmAudit?.[0].after as {cash:number}).cash,500);assert.throws(()=>gmMutate(w,{playerId:p.id,revision:3,action:'addCash',amount:1.2},now+4));});
