import {test} from 'node:test';import assert from 'node:assert/strict';import {ZONES,NPCS,portalsFor} from '../shared/content';import {interactionAt} from '../shared/interactions';import {createWorld,newPlayer,applyInput,tickWorld} from '../server/engine';
const now=1800000000000;function setup(){const w=createWorld(now),p=newPlayer('plaza','광장검증',0,now);w.players[p.id]=p;return {w,p};}
test('world orb and every town exit win E targeting; pet keeper does not cover portals',()=>{for(const zone of [0,28,29]){for(const [id,portal] of portalsFor(zone).entries())assert.deepEqual(interactionAt(zone,portal),{kind:'portal',id,distance:0});const pet=NPCS.find(n=>n.zone===zone&&n.service==='pets')!;assert.equal(interactionAt(zone,pet)?.id,pet.id);assert.ok(portalsFor(zone).every(p=>Math.hypot(p.x-pet.x,p.y-pet.y)>200));}});
test('both new plazas have no monsters and reuse all nine NPC services',()=>{const {w}=setup();for(const zone of [28,29]){assert.ok(ZONES[zone].safe);assert.ok(!ZONES[zone].raid);assert.equal(w.monsters.filter(m=>m.zone===zone).length,0);assert.equal(NPCS.filter(n=>n.zone===zone).length,9);}});
test('plaza travel validates level; raid IDs remain blocked from world map travel',()=>{const {w,p}=setup();applyInput(w,p,{seq:1,action:'travel',value:28},now+1000);assert.equal(p.zone,0);p.level=18;applyInput(w,p,{seq:2,action:'travel',value:28},now+1200);assert.equal(p.zone,28);applyInput(w,p,{seq:3,action:'travel',value:29},now+1400);assert.equal(p.zone,28);p.level=28;applyInput(w,p,{seq:4,action:'travel',value:29},now+1600);assert.equal(p.zone,29);applyInput(w,p,{seq:5,action:'travel',value:25},now+1800);assert.equal(p.zone,29);});
test('new safe plazas reject attacks, heal naturally and provide local shop, healing and quests',()=>{const {w,p}=setup();p.zone=28;p.hp=10;tickWorld(w,now+1000);assert.ok(p.hp>10);applyInput(w,p,{seq:1,skill:0,tx:1000,ty:740},now+1200);assert.match(p.notice,/마을/);const healer=NPCS.find(n=>n.zone===28&&n.service==='heal')!;p.x=healer.x;p.y=healer.y;applyInput(w,p,{seq:2,action:'heal'},now+1400);assert.ok(p.hp>100);const shop=NPCS.find(n=>n.zone===28&&n.service==='shop')!;p.x=shop.x;p.y=shop.y;applyInput(w,p,{seq:3,action:'buy',value:-1},now+1600);assert.equal(p.potions,11);const guide=NPCS.find(n=>n.zone===28&&n.service==='quest')!;p.x=guide.x;p.y=guide.y;applyInput(w,p,{seq:4,action:'quest',value:0},now+1800);assert.equal(p.quests[0],0);});
test('uploaded winter and hell music is assigned to the new plazas and matching hunting maps',()=>{assert.equal(ZONES[28].music,8);assert.equal(ZONES[29].music,10);assert.equal(ZONES[12].music,9);assert.equal(ZONES[19].music,11);});

test('direct plaza travel works from raid maps without portal proximity',()=>{const {w,p}=setup();p.level=28;p.zone=25;p.x=900;p.y=700;applyInput(w,p,{seq:1,action:'travel',value:28},now+1000);assert.equal(p.zone,28);p.zone=27;p.x=1200;p.y=850;applyInput(w,p,{seq:2,action:'travel',value:29},now+1200);assert.equal(p.zone,29);});
