import {test} from 'node:test';import assert from 'node:assert/strict';
import {gameInput,sameOrigin,requestBody} from '../server/request';
import {createWorld,newPlayer,snapshot} from '../server/engine';
import {ownedPlayer,roster} from '../shared/accounts';
test('malformed numeric, oversized and structured inputs are rejected before mutation',()=>{for(const body of [{seq:1,moveX:Infinity},{seq:1,value:NaN},{seq:1,skill:0.5},{seq:1,indices:[-1]},{seq:1,indices:Array(13).fill(0)},{seq:1,targetId:{}},{seq:1,chat:'x'.repeat(161)},{seq:'1'},[]])assert.throws(()=>gameInput(body as any));const i=gameInput({seq:1,action:'cashBuy',value:12,gold:0,cash:999999,gmSkin:8,inventory:[42]});assert.equal((i as any).cash,undefined);assert.equal((i as any).gmSkin,undefined);assert.equal((i as any).inventory,undefined);});
test('unsafe requests require exact scheme and origin and malformed origins fail closed',()=>{for(const origin of [undefined,'https://foreign.example','http://game.example','invalid'])assert.equal(sameOrigin(new Request('https://game.example/api/game',{method:'POST',headers:origin?{Origin:origin}:{}})),false);assert.equal(sameOrigin(new Request('https://game.example/api/game',{method:'POST',headers:{Origin:'https://game.example'}})),true);assert.equal(sameOrigin(new Request('https://game.example/api/game')),true);});
test('body parser rejects null arrays and oversized payloads',async()=>{for(const text of ['null','[]','"string"','x'.repeat(5000)])await assert.rejects(requestBody(new Request('https://game.example',{method:'POST',body:text})));});
test('remote player snapshots hide wallets, inventory and storage while retaining visible cosmetics',()=>{const now=1800000000000,w=createWorld(now),a=newPlayer('a','자신',0,now),b=newPlayer('b','다른이',1,now);b.gold=999;b.cash=888;b.inventory=[20];b.storage=[21];b.animalSkinId=3;w.players={a,b};const remote=snapshot(w,a,now).players[0];assert.equal(remote.cash,undefined);assert.equal(remote.gold,0);assert.deepEqual(remote.inventory,[]);assert.equal(remote.storage,undefined);assert.equal(remote.animalSkinId,3);assert.equal(b.cash,888);assert.deepEqual(b.inventory,[20]);});
test('anonymous roster reads allocate no permanent accounts and foreign IDs cannot be selected',()=>{const w=createWorld(1800000000000);for(let i=0;i<100;i++){assert.equal(ownedPlayer(w,'stranger'+i,'a'),undefined);assert.deepEqual(roster(w,'stranger'+i).characters,[]);}assert.equal(Object.keys(w.accounts||{}).length,0);});
