'use strict';
const $=id=>document.getElementById(id),state={players:[],items:[],classes:[],zones:[],selected:null,detail:null,dirty:new Set(),revision:null,busy:false,logged:false};
const text=(id,value)=>{$(id).textContent=value;};
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok){if(r.status===401&&path!=='login')showLogin();throw new Error(data.error||'요청 실패');}return data;}
function showLogin(){state.logged=false;$('login').hidden=false;$('dashboard').hidden=true;}
function message(value,error=false){text('feedback',value);$('feedback').className='message'+(error?' error':'');}
function showDashboard(){state.logged=true;$('login').hidden=true;$('dashboard').hidden=false;void refresh();}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('login',{code:$('code').value});$('code').value='';showDashboard();}catch(e){text('login-message',e.message);}});
$('logout').onclick=async()=>{await api('logout',{});showLogin();};$('backup').onclick=()=>{location.href='/api/backup';};
function renderPlayers(){const list=$('players');list.replaceChildren();const filtered=state.players.filter(p=>!$('online-only').checked||p.online);for(const p of filtered){const row=document.createElement('button');row.className='player-row'+(p.id===state.selected?' selected':'');const icon=document.createElement('span');icon.className='avatar';icon.textContent=['⚔','➶','✦'][p.classId];const info=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small'),dot=document.createElement('i');name.textContent=p.name;meta.textContent='LV. '+p.level+' · '+(state.classes[p.classId]?.name||'수호자')+(p.banned?' · 차단':'');dot.className='presence'+(p.online?' online':'');info.append(name,meta);row.append(icon,info,dot);row.onclick=()=>{state.selected=p.id;state.dirty.clear();state.revision=null;message('');void loadDetail();renderPlayers();};list.append(row);}if(!filtered.length){const p=document.createElement('p');p.className='muted';p.textContent='조건에 맞는 캐릭터가 없습니다.';list.append(p);}}
async function refresh(){if(!state.logged||state.busy)return;try{const s=await api('players?q='+encodeURIComponent($('search').value));state.players=s.players;state.items=s.items;state.classes=s.classes;state.zones=s.zones;text('online',s.online);text('total',s.players.length);text('connection','● 연결됨 · '+new Date(s.now).toLocaleTimeString('ko-KR'));renderPlayers();if(state.selected)await loadDetail();}catch(e){text('connection','● '+e.message);}}
async function loadDetail(){if(state.busy)return;try{const selected=state.selected;const p=await api('player?id='+encodeURIComponent(selected));if(state.selected!==selected)return;state.detail=p;$('empty').hidden=true;$('detail').hidden=false;text('player-name',p.name);text('selected-name',p.name);text('player-class',state.classes[p.classId]?.name||'수호자');text('player-id',p.id);text('selected-meta','LV. '+p.level+' · '+(state.zones[p.zone]?.name||'알 수 없는 지역'));text('player-status',p.banned?'접속 차단':p.online?'접속 중':'오프라인');
 if(state.revision===null||!state.dirty.size)state.revision=p.revision;for(const field of ['level','xp','gold','cash','potions','manaPotions'])if(!state.dirty.has(field))$(field).value=p[field]??0;text('xp-hint','다음 레벨 필요 경험치 '+p.needXp.toLocaleString()+' · 현재 레벨 경험치는 이 값 미만으로 입력하세요.');
 const select=$('item-id');if(!select.options.length)for(const item of state.items){const o=document.createElement('option');o.value=item.id;o.textContent='#'+item.id+' · '+item.name;select.append(o);}
 text('bag-count',p.inventory.length+' / 60');const counts=new Map();for(const id of p.inventory)counts.set(id,(counts.get(id)||0)+1);$('inventory').replaceChildren();for(const [id,n] of counts){const row=document.createElement('div');row.className='inventory-row';const name=document.createElement('span'),amount=document.createElement('small');name.textContent=(state.items[id]?.name||'#'+id)+(Object.values(p.equipment).includes(id)?' · 장착':'');amount.textContent='× '+n;row.append(name,amount);$('inventory').append(row);}if(!counts.size)text('inventory','가방이 비어 있습니다.');$('vitals').replaceChildren();for(const str of ['HP '+Math.round(p.hp)+' / '+p.stats.hp,'MP '+Math.round(p.mp)+' / '+p.stats.mp,'공격력 '+p.stats.atk,'방어력 '+p.stats.def,'보유 캐시 '+(p.cash||0)+' C']){const node=document.createElement('span');node.textContent=str;$('vitals').append(node);}
 }catch(e){message(e.message,true);}}
for(const field of ['level','xp','gold','cash','potions','manaPotions'])$(field).addEventListener('input',()=>{state.dirty.add(field);if(field==='level'){state.dirty.add('xp');$('xp').value=0;}});
$('reset-draft').onclick=()=>{state.dirty.clear();state.revision=null;void loadDetail();};
async function act(action,values={}){if(!state.selected||state.busy)return;state.busy=true;$('detail').classList.add('busy');try{const result=await api('action',{playerId:state.selected,revision:state.revision,action,reason:$('reason').value,...values});state.revision=result.player.revision;state.dirty.clear();message('✓ 수정 내용을 서버에 저장하고 게임 화면에 반영했습니다.');}catch(e){message(e.message,true);}finally{state.busy=false;$('detail').classList.remove('busy');void loadDetail();}}
$('stats-form').addEventListener('submit',e=>{e.preventDefault();const values={};for(const key of state.dirty)values[key]=Number($(key).value);if(!state.dirty.size){message('변경할 수치를 입력하세요.',true);return;}void act('set',values);});
$('grant-cash').onclick=()=>act('addCash',{amount:Number($('add-cash').value)});$('grant-xp').onclick=()=>act('addXp',{amount:Number($('add-xp').value)});$('grant-gold').onclick=()=>act('addGold',{amount:Number($('add-gold').value)});$('give-item').onclick=()=>act('giveItem',{itemId:Number($('item-id').value),quantity:Number($('quantity').value)});$('remove-item').onclick=()=>act('removeItem',{itemId:Number($('item-id').value),quantity:Number($('quantity').value)});document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>act(button.dataset.action));
$('search').oninput=()=>void refresh();$('online-only').onchange=renderPlayers;
$('audit-button').onclick=async()=>{try{const data=await api('audit');$('audit-list').replaceChildren();for(const entry of data.entries){const row=document.createElement('article');row.className='audit-row';const time=document.createElement('time'),name=document.createElement('strong'),description=document.createElement('span'),details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');time.textContent=new Date(entry.at).toLocaleString('ko-KR');name.textContent=entry.name;description.textContent=entry.action+(entry.reason?' · '+entry.reason:'');summary.textContent='변경 전 / 후 보기';pre.textContent=JSON.stringify({before:entry.before,after:entry.after},null,2);details.append(summary,pre);row.append(time,name,description,details);$('audit-list').append(row);}if(!data.entries.length)text('audit-list','아직 관리자 변경 기록이 없습니다.');$('audit-dialog').showModal();}catch(e){message(e.message,true);}};$('close-audit').onclick=()=>$('audit-dialog').close();
setInterval(()=>void refresh(),1500);void api('session').then(s=>s.authenticated?showDashboard():showLogin()).catch(showLogin);

async function loadDonations(){const data=await api('donations');$('donation-list').replaceChildren();if(document.activeElement!==$('donation-guide'))$('donation-guide').value=data.settings.donationGuide;if(document.activeElement!==$('donation-url'))$('donation-url').value=data.settings.donationUrl;for(const d of data.requests){const row=document.createElement('article');row.className='donation-row';const title=document.createElement('strong'),info=document.createElement('span'),ref=document.createElement('p'),actions=document.createElement('div');title.textContent=d.name+' · '+d.won.toLocaleString()+'원 / '+d.cash+' C';info.textContent=new Date(d.created).toLocaleString('ko-KR')+' · '+d.status;ref.textContent='확인 정보: '+d.reference;row.append(title,info,ref);if(d.status==='pending'){const check=document.createElement('input');check.type='checkbox';const label=document.createElement('label');label.append(check,document.createTextNode('실제 입금·결제를 확인했습니다'));const approve=document.createElement('button'),reject=document.createElement('button');approve.textContent='확인 후 캐시 지급';approve.className='primary';approve.disabled=true;check.onchange=()=>approve.disabled=!check.checked;reject.textContent='거절';const process=async value=>{approve.disabled=true;reject.disabled=true;try{await api('donation',{id:d.id,revision:d.revision,approve:value,confirmReceived:check.checked});text('donation-feedback',value?'캐시를 지급했습니다.':'확인 요청을 거절했습니다.');await loadDonations();void refresh();}catch(e){text('donation-feedback',e.message);approve.disabled=!check.checked;reject.disabled=false;}};approve.onclick=()=>void process(true);reject.onclick=()=>void process(false);actions.append(approve,reject);row.append(label,actions);}else{const done=document.createElement('span');done.textContent=d.status==='approved'?'캐시 지급 완료':'확인 거절';row.append(done);}$('donation-list').append(row);}if(!data.requests.length)text('donation-list','확인을 기다리는 후원 요청이 없습니다.');}
$('donations-button').onclick=()=>void loadDonations().then(()=>$('donation-dialog').showModal()).catch(e=>message(e.message,true));$('close-donations').onclick=()=>$('donation-dialog').close();$('donation-settings').onsubmit=async e=>{e.preventDefault();try{await api('settings',{donationGuide:$('donation-guide').value,donationUrl:$('donation-url').value});text('donation-feedback','후원 안내를 저장하고 유저 화면에 반영했습니다.');}catch(e){text('donation-feedback',e.message);}};
