import {RAIDS} from '../shared/social';
import {PROMOTION_TRIALS} from '../shared/promotion';
import {CLASSES,ITEMS,MONSTERS,isBoss,ZONES,QUESTS,WORLD,zoneScale,skillUnlocked} from '../shared/content';
import {DODGE,SKILL_SPECS} from '../shared/skills';
import {addXp,stats} from '../shared/progression';
import {aimDirection,clearSight,distance,inCone,lineDistance,sweepMove} from '../shared/physics';
import type {Event,Input,Monster,Player,World} from '../shared/types';
export function emit(w:World,p:{zone:number;x:number;y:number},now:number,kind:Event['kind'],value:number,color:string,extra:Partial<Event>={}){w.events.push({id:crypto.randomUUID(),time:now,zone:p.zone,x:p.x,y:p.y,kind,value,color,...extra});}
export function killMonster(w:World,m:Monster,p:Player,now:number){if(ZONES[m.zone]?.raid){const b=w.raids?.find(b=>b.zone===m.zone),r=RAIDS[m.zone-25];m.deadUntil=Number.MAX_SAFE_INTEGER;if(b&&!b.rewarded){b.rewarded=true;b.status='won';b.ends=now+30000;for(const id of b.participants){const a=w.players[id];if(!a||a.zone!==m.zone||now-a.seen>15000||!(m.raidDamage?.[id]))continue;a.gold+=r.gold;a.raidWins=(a.raidWins||0)+1;if(a.inventory.length<60)a.inventory.push(14+a.classId);else{a.raidRewards??=[];a.raidRewards.push(14+a.classId);}if(addXp(a,r.xp))emit(w,a,now,'level',a.level,'#ffe8a3',{source:a.id});a.notice=r.name+' 처치! '+r.gold+' G · '+r.xp+' EXP'+(a.inventory.length<=60?' 전설 무기 지급 · 가방이 가득 차면 레이드 창에서 수령':'');}emit(w,m,now,'death',0,'#ffdf9e',{effect:'raid-death'});}return;}m.deadUntil=now+(m.type===9?60000:15000);const md=MONSTERS[m.type];const participants=Object.values(w.players).filter(a=>a.zone===m.zone&&a.hp>0&&now-a.seen<10000&&distance(a,m)<500);for(const a of participants){a.kills[m.type]=(a.kills[m.type]||0)+1;if(a.promotionQuest){const trial=PROMOTION_TRIALS[a.promotionQuest.tier-1];if(m.zone===trial.zone&&m.type===trial.monster)a.promotionQuest.kills=Math.min(trial.count,a.promotionQuest.kills+1);if(m.zone===trial.bossZone&&m.type===trial.boss)a.promotionQuest.bosses=Math.min(trial.bossCount,a.promotionQuest.bosses+1);}for(const q of QUESTS){if((q.zone===undefined||q.zone===m.zone)&&q.monster===m.type&&a.quests[q.id]!==undefined)a.quests[q.id]=Math.min(q.count,a.quests[q.id]+1);}if(addXp(a,Math.round(md.xp*zoneScale(m.zone))))emit(w,a,now,'level',a.level,'#ffe8a3',{source:a.id});}const rarity=isBoss(m.type)?2:m.zone>=2?1:0;const pool=ITEMS.filter(i=>i.id>=21&&(i.minLevel||1)<=ZONES[m.zone].minLevel&&i.rarity<=rarity+1);const item=Math.random()<.48||isBoss(m.type)?(pool.length&&Math.random()<.5?pool[Math.floor(Math.random()*pool.length)].id:rarity*7+Math.floor(Math.random()*7)):null;w.loot.push({id:crypto.randomUUID(),owner:p.id,zone:m.zone,x:m.x,y:m.y,gold:Math.round(md.gold*zoneScale(m.zone)),item,potion:Math.random()<.35,expires:now+60000});emit(w,m,now,'death',0,'#b7ecd9');}
export function damageMonster(w:World,m:Monster,p:Player,damage:number,now:number,critical=false,effect?:string){if(m.hp<=0)return;damage=Math.max(1,Math.round(damage));if(ZONES[m.zone]?.raid){m.raidDamage??={};m.raidDamage[p.id]=(m.raidDamage[p.id]||0)+Math.min(m.hp,damage);}m.hp=Math.max(0,m.hp-damage);m.lastHit=now;emit(w,m,now,'hit',damage,critical?'#ffe7a4':effect==='burn'?'#ffb072':'#fff5e0',{critical,effect,source:p.id});if(m.hp<=0)killMonster(w,m,p,now);}
export function hurtPlayer(w:World,p:Player,damage:number,now:number){if(p.hp<=0||(p.dodgeUntil||0)>now)return;const value=Math.max(2,Math.round(damage-stats(p).def*.6));p.hp=Math.max(0,p.hp-value);emit(w,p,now,'hit',value,'#ff8e87',{source:p.id,effect:'player-hurt'});if(p.hp<=0)p.notice='쓰러졌습니다. 별샘 마을에서 다시 일어날 수 있습니다.';}
function applyStatus(m:Monster,p:Player,skill:number,now:number){const spec=SKILL_SPECS[p.classId][skill],rank=p.skillRanks?.[skill]||0;if(spec.burn){m.burnUntil=now+spec.burn;m.burnOwner=p.id;m.burnTick=now+650;}if(spec.freeze){if(m.type!==9)m.freezeUntil=now+spec.freeze+rank*100;m.slowUntil=now+4000;}if(spec.stun&&m.type!==9)m.stunUntil=now+spec.stun+rank*80;}
export function castSkill(w:World,p:Player,input:Input,now:number){const skill=input.skill;if(!Number.isInteger(skill)||skill!<0||skill!>11)return;const i=skill!,c=CLASSES[p.classId],spec=SKILL_SPECS[p.classId][i];if(!skillUnlocked(p,i)){p.notice='스킬 창에서 레벨 조건을 확인하고 스킬을 배우세요.';return;}if(ZONES[p.zone]?.safe){p.notice='마을에서는 무기를 내려놓으세요.';return;}if(now<(p.cd[i]||0))return;if(p.mp<c.cost[i]){p.notice='마나가 부족합니다. R 키로 마나 물약을 사용하세요.';return;}
 p.mp-=c.cost[i];p.cd[i]=now+c.cd[i];p.attackAt=now;p.attackSkill=i;let aim={x:Math.max(0,Math.min(WORLD.w,Number(input.tx)||p.x+100)),y:Math.max(0,Math.min(WORLD.h,Number(input.ty)||p.y))};const origin={x:p.x,y:p.y,zone:p.zone};const dir=aimDirection(p,aim);if(Math.abs(dir.x)>.1)p.face=dir.x>0?1:-1;p.target=aim;
 if(p.classId===0&&i===0){p.combo=now<(p.comboUntil||0)?((p.combo||0)%3)+1:1;p.comboUntil=now+1800;}
 if(spec.dash){sweepMove(p,dir.x*spec.dash,dir.y*spec.dash);}if(spec.invulnerable)p.dodgeUntil=now+spec.invulnerable;
 const rank=p.skillRanks?.[i]||0,power=c.power[i]*(1+rank*.12)*(p.classId===0&&i===0&&p.combo===3?1.55:1);
 const candidates=w.monsters.filter(m=>m.zone===p.zone&&m.hp>0&&distance(m,origin)<=c.range[i]&&clearSight(origin,m)).sort((a,b)=>distance(a,aim)-distance(b,aim));
 if(spec.shape==='meteor'){const d=distance(origin,aim);if(d>c.range[i])aim={x:origin.x+dir.x*c.range[i],y:origin.y+dir.y*c.range[i]};if(!clearSight(origin,aim)){p.notice='별빛이 닿지 않는 위치입니다.';p.mp+=c.cost[i];p.cd[i]=now;return;}w.casts??=[];w.casts.push({id:crypto.randomUUID(),source:p.id,zone:p.zone,x:aim.x,y:aim.y,resolveAt:now+700,radius:spec.radius!,skill:i});emit(w,{...aim,zone:p.zone},now,'warning',spec.radius!,'#c4afff',{classId:p.classId,source:p.id,skill:i,effect:'meteor'});return;}
 let victims:Monster[]=[];
 if(spec.shape==='single')victims=candidates.slice(0,1);
 if(spec.shape==='circle')victims=candidates;
 if(spec.shape==='cone')victims=candidates.filter(m=>inCone(origin,m,aim,p.classId===1?.52:-.2)).slice(0,p.classId===1?5:6);
 if(spec.shape==='line')victims=candidates.filter(m=>{const l=lineDistance(origin,m,aim);return l.along>=-20&&l.across<(p.classId===0?75:38);});
 if(spec.shape==='target-circle'){const target=candidates[0];aim=target?{x:target.x,y:target.y}:aim;victims=w.monsters.filter(m=>m.zone===p.zone&&m.hp>0&&distance(m,aim)<=spec.radius!&&distance(m,origin)<=c.range[i]+spec.radius!&&clearSight(origin,m));}
 emit(w,origin,now,'spell',p.classId===0&&i===0?p.combo||1:0,c.color,{source:p.id,tx:aim.x,ty:aim.y,skill:i,classId:p.classId,effect:spec.shape});let healed=0;
 for(const m of victims){const critical=Math.random()<.14;const damage=Math.round(stats(p).atk*power*(critical?1.6:1)*(.9+Math.random()*.2));const actual=Math.min(m.hp,damage);applyStatus(m,p,i,now);damageMonster(w,m,p,damage,now,critical);if(spec.lifeSteal)healed+=actual*spec.lifeSteal;const d=distance(m,p);if(d>0&&m.type!==9&&!(spec.freeze)){sweepMove(m,(m.x-p.x)/d*14,(m.y-p.y)/d*14);}}
 if(healed>0){const amount=Math.max(1,Math.round(healed));p.hp=Math.min(stats(p).hp,p.hp+amount);emit(w,p,now,'heal',amount,'#a0f4ae',{source:p.id});}
}
export function dodge(w:World,p:Player,input:Input,now:number){if(now<(p.dodgeCd||0)){p.notice='회피가 아직 준비되지 않았습니다.';return;}const dx=Number(input.dx)||0,dy=Number(input.dy)||0;const aim=dx||dy?{x:p.x+dx,y:p.y+dy}:{x:Number(input.tx)||p.x+p.face*100,y:Number(input.ty)||p.y};const dir=aimDirection(p,aim);const origin={x:p.x,y:p.y,zone:p.zone};sweepMove(p,dir.x*DODGE.distance,dir.y*DODGE.distance);p.dodgeUntil=now+DODGE.invulnerable;p.dodgeCd=now+DODGE.cooldown;emit(w,origin,now,'dodge',0,'#c2e8de',{source:p.id,tx:p.x,ty:p.y,classId:p.classId});}
export function tickCombat(w:World,now:number){for(const cast of w.casts||[]){if(now<cast.resolveAt)continue;const p=w.players[cast.source];if(!p)continue;const skill=cast.skill,rank=p.skillRanks?.[skill]||0;for(const m of w.monsters){if(m.zone!==cast.zone||m.hp<=0||distance(m,cast)>cast.radius||!clearSight(cast,m))continue;applyStatus(m,p,skill,now);damageMonster(w,m,p,stats(p).atk*CLASSES[p.classId].power[skill]*(1+rank*.12),now);}emit(w,cast,now,'spell',0,'#dec6ff',{skill,classId:p.classId,source:p.id,effect:'meteor',tx:cast.x,ty:cast.y});}w.casts=(w.casts||[]).filter(c=>now<c.resolveAt);
 for(const m of w.monsters){if(m.hp<=0)continue;if((m.burnUntil||0)>now&&now>=(m.burnTick||0)){const p=w.players[m.burnOwner||''];if(p){damageMonster(w,m,p,stats(p).atk*.2,now,false,'burn');m.burnTick=now+650;}}
 if(m.hp<=0)continue;if(m.attackUntil&&now>=m.attackUntil){for(const p of Object.values(w.players)){if(p.zone===m.zone&&p.hp>0&&now-p.seen<10000&&distance(p,{x:m.attackX!,y:m.attackY!})<170)hurtPlayer(w,p,(ZONES[m.zone]?.raid?RAIDS[m.zone-25].atk:MONSTERS[m.type].atk*zoneScale(m.zone))*(m.hp<m.maxHp*.5?2.1:1.65),now);}emit(w,{zone:m.zone,x:m.attackX!,y:m.attackY!},now,'spell',0,'#ff876b',{effect:'boss-slam'});m.attackUntil=0;}
 }
}
