import {loadDamageAtlas} from './damageSprites';
// The generated atlas has unequal row heights. Explicit source regions preserve full silhouettes.
// NPCs use independent transparent assets and never share an atlas crop.
export const NPC_ART:Record<number,string>={3:'/art/npc-sera.png',14:'/art/npc-roen.png',15:'/art/npc-elin.png'};
export const ATLAS_ROWS=[0,.258,.468,.692,1];
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Unable to load '+src));i.src=src;});}
export function fitSprite(image:HTMLImageElement,region:{x:number;y:number;w:number;h:number},blackKey:boolean,scaleOverride?:number){const raw=document.createElement('canvas');raw.width=Math.ceil(region.w);raw.height=Math.ceil(region.h);const ctx=raw.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(image,region.x,region.y,region.w,region.h,0,0,raw.width,raw.height);const pixels=ctx.getImageData(0,0,raw.width,raw.height),d=pixels.data;let left=raw.width,top=raw.height,right=0,bottom=0;
 for(let y=0;y<raw.height;y++)for(let x=0;x<raw.width;x++){const i=(y*raw.width+x)*4;if(blackKey){const brightness=Math.max(d[i],d[i+1],d[i+2]);if(brightness<18)d[i+3]=0;else if(brightness<38)d[i+3]=Math.round((brightness-18)/20*255);}if(d[i+3]>64){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y);}}
 ctx.putImageData(pixels,0,0);const out=document.createElement('canvas');out.width=512;out.height=512;const output=out.getContext('2d')!;if(left>right)return out;left=Math.max(0,left-5);top=Math.max(0,top-5);right=Math.min(raw.width-1,right+5);bottom=Math.min(raw.height-1,bottom+5);const w=right-left+1,h=bottom-top+1,scale=scaleOverride??460/Math.max(w,h);output.drawImage(raw,left,top,w,h,(512-w*scale)/2,492-h*scale,w*scale,h*scale);return out;
}
export async function loadArt(){void loadDamageAtlas();const [forest,atlas,...npcs]=await Promise.all([loadImage('/art/forest.png'),loadImage('/art/atlas.png'),...Object.values(NPC_ART).map(loadImage)]);const sprites=Array.from({length:16},(_,n)=>{const row=Math.floor(n/4),x=(n%4)*atlas.width/4,y=ATLAS_ROWS[row]*atlas.height;return fitSprite(atlas,{x,y,w:atlas.width/4,h:(ATLAS_ROWS[row+1]-ATLAS_ROWS[row])*atlas.height},true);});// Skeleton shield, stone golem arms and bat wings cross the original equal columns.
 const regions:Record<number,{x:number;y:number;w:number;h:number}>={9:{x:.25,y:.468,w:.228,h:.220},10:{x:.479,y:.468,w:.259,h:.230},11:{x:.738,y:.468,w:.262,h:.220}};for(const [index,r] of Object.entries(regions))sprites[Number(index)]=fitSprite(atlas,{x:r.x*atlas.width,y:r.y*atlas.height,w:r.w*atlas.width,h:r.h*atlas.height},true);Object.keys(NPC_ART).forEach((index,i)=>{const image=npcs[i];sprites[Number(index)]=fitSprite(image,{x:0,y:0,w:image.width,h:image.height},false);});const monsterSheet=await loadImage('/art/monster-motion-v13.png');
 // Cuts measured in transparent gutters, rather than guessed equal columns.
 // One scale and a fixed row origin keep body size and vertical position stable.
 const monsterCuts=[[0,331,653,963,1254],[0,329,632,944,1254],[0,320,634,943,1254],[0,323,626,939,1254]];
 const monsterAnimations:Record<number,HTMLCanvasElement[]>={};
 for(let row=0;row<4;row++){
  const cuts=monsterCuts[row].map(x=>x*monsterSheet.width/1254),h=monsterSheet.height/4;
  const scale=460/Math.max(h,...cuts.slice(0,-1).map((x,i)=>cuts[i+1]-x));
  const frames=Array.from({length:4},(_,i)=>{const frame=document.createElement('canvas');frame.width=512;frame.height=512;
   const w=cuts[i+1]-cuts[i];frame.getContext('2d')!.drawImage(monsterSheet,cuts[i],row*h,w,h,(512-w*scale)/2,492-h*scale,w*scale,h*scale);return frame;});
  const sprite=[11,22,23,24][row];monsterAnimations[sprite]=frames;sprites[sprite]=frames[0];
 }
 const batFrames=monsterAnimations[11];const workshop=await loadImage('/art/npc-workshops.png');for(let n=0;n<6;n++)sprites[16+n]=fitSprite(workshop,{x:n%3*workshop.width/3,y:Math.floor(n/3)*workshop.height/2,w:workshop.width/3,h:workshop.height/2},false);const [snow,ember,...sheets]=await Promise.all(['/art/snow.png','/art/ember.png','/art/knight-motion.png','/art/ranger-motion.png','/art/mage-motion.png'].map(loadImage));
 // Generated poses have clear row gaps but imperfect equal-row baselines. Explicit gaps
 // preserve toes and weapons, and one scale per sheet avoids frame-to-frame size jitter.
 const rowCuts=[0,385,750,1086],baselines=[[342,720,1035],[360,713,1030],[362,728,1022]];
 const animations=sheets.map((sheet,cls)=>Array.from({length:12},(_,i)=>{const frame=document.createElement('canvas');frame.width=512;frame.height=512;const row=Math.floor(i/4),w=sheet.width/4,y=rowCuts[row],h=rowCuts[row+1]-y,scale=1.28;frame.getContext('2d')!.drawImage(sheet,(i%4)*w,y,w,h,(512-w*scale)/2,488-(baselines[cls][row]-y)*scale,w*scale,h*scale);return frame;}));animations.forEach((frames,i)=>{sprites[i]=frames[0];});const [petSheet,eliteSheet]=await Promise.all([loadImage('/art/pet-motion.png'),loadImage('/art/elite-monsters.png')]);for(let i=0;i<2;i++)sprites[12+i]=fitSprite(eliteSheet,{x:i===0?0:735,y:0,w:i===0?735:eliteSheet.width-735,h:eliteSheet.height},false);const petCuts=[0,320,650,1024];const pets=Array.from({length:3},(_,pet)=>Array.from({length:4},(_,index)=>{const frame=document.createElement('canvas');frame.width=512;frame.height=512;const w=petSheet.width/4,y=petCuts[pet],h=petCuts[pet+1]-y,scale=460/Math.max(w,h);frame.getContext('2d')!.drawImage(petSheet,index*w,y,w,h,(512-w*scale)/2,492-h*scale,w*scale,h*scale);return frame;}));const [raid,winterPlaza,emberPlaza]=await Promise.all(['/art/raid-arena.png','/art/winter-plaza.png','/art/ember-plaza.png'].map(loadImage));return {monsterAnimations,batFrames,plazas:{28:winterPlaza,29:emberPlaza} as Record<number,HTMLImageElement>,raid,forest,sprites,biomes:[forest,snow,ember],animations,pets};}
