import type {Snapshot} from '../../shared/types';
function ring(ctx:CanvasRenderingContext2D,x:number,y:number,r:number,color:string,alpha:number,line=2){ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.lineWidth=line;ctx.beginPath();ctx.ellipse(x,y,r,r*.55,0,0,Math.PI*2);ctx.stroke();}
export function drawTelegraphs(ctx:CanvasRenderingContext2D,s:Snapshot,now:number){for(const m of s.monsters){if(!m.attackUntil||m.attackUntil<=now||m.hp<=0)continue;const remaining=m.attackUntil-now,x=m.attackX!,y=m.attackY!;ctx.save();ctx.fillStyle=`rgba(233,66,43,${.1+(1-remaining/1200)*.17})`;ctx.beginPath();ctx.arc(x,y,170,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ff9a74';ctx.lineWidth=3;ctx.setLineDash([14,9]);ctx.beginPath();ctx.arc(x,y,170,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#ffc8a2';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x,y,170,-Math.PI/2,-Math.PI/2+(1-remaining/1200)*Math.PI*2);ctx.stroke();ctx.restore();}
 for(const cast of s.casts||[]){if(now>=cast.resolveAt)continue;ctx.save();const t=1-(cast.resolveAt-now)/700;ctx.fillStyle='#b999ef22';ctx.beginPath();ctx.arc(cast.x,cast.y,cast.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d5b7ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(cast.x,cast.y,cast.radius,0,Math.PI*2);ctx.stroke();ctx.lineWidth=4;ctx.beginPath();ctx.arc(cast.x,cast.y,cast.radius,-Math.PI/2,-Math.PI/2+t*Math.PI*2);ctx.stroke();ctx.restore();}}
export function drawEffects(ctx:CanvasRenderingContext2D,s:Snapshot,now:number){for(const e of s.events){const age=now-e.time;if(age<0||age>1500||e.kind==='hit'||e.kind==='heal'||e.kind==='warning')continue;const alpha=1-age/1500;ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle=e.color;ctx.fillStyle=e.color;
 if(e.kind==='dodge'&&age<440){const t=age/440;ctx.globalAlpha=1-t;ctx.lineWidth=2;for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(e.x-8+i*5,e.y-35+i*10);ctx.lineTo((e.tx||e.x)-8+i*5,(e.ty||e.y)-35+i*10);ctx.stroke();}ctx.restore();continue;}
 if(e.kind==='spell'&&age<750){const t=Math.min(1,age/230),tx=e.tx??e.x,ty=e.ty??e.y,angle=Math.atan2(ty-e.y,tx-e.x);ctx.globalAlpha=1-age/750;ctx.shadowColor=e.color;ctx.shadowBlur=18;
 if(e.effect==='boss-slam'||e.effect==='meteor'){const r=e.effect==='meteor'?165:170;ctx.globalAlpha=(1-age/750)*.75;const g=ctx.createRadialGradient(e.x,e.y,5,e.x,e.y,r+age*.12);g.addColorStop(0,e.color+'99');g.addColorStop(.35,e.color+'45');g.addColorStop(1,e.color+'00');ctx.fillStyle=g;ctx.fillRect(e.x-r-80,e.y-r-80,(r+80)*2,(r+80)*2);ring(ctx,e.x,e.y,r*.2+age*.18,e.color,1-age/750,5);if(e.effect==='meteor'&&age<250){ctx.strokeStyle='#fff2ff';ctx.lineWidth=12*(1-age/250);ctx.beginPath();ctx.moveTo(e.x,e.y-380+age);ctx.lineTo(e.x,e.y);ctx.stroke();}}
 else if(e.classId===0){const r=e.skill===2?75+age*.17:e.skill===3?105:60+e.value*10;ctx.lineWidth=e.skill===2?5:4;for(let i=0;i<(e.skill===2?3:2);i++){ctx.beginPath();ctx.arc(e.x,e.y-20,r-i*14,angle-.9+age/250*(e.skill===2?3:1),angle+1.1+age/250*(e.skill===2?3:1));ctx.stroke();}if(e.skill===3){ctx.lineWidth=10;ctx.globalAlpha=(1-age/750)*.4;ctx.beginPath();ctx.moveTo(e.x,e.y-25);ctx.lineTo(e.x+Math.cos(angle)*180,e.y-25+Math.sin(angle)*180);ctx.stroke();}}
 else if(e.classId===2&&e.skill===2){ring(ctx,e.x,e.y,30+age*.3,'#b7f0ff',1-age/750,4);ring(ctx,e.x,e.y,10+age*.26,'#d3f8ff',.6*(1-age/750),2);}
 else if(e.classId===2&&e.skill===1){const r=115;const g=ctx.createRadialGradient(tx,ty,2,tx,ty,r);g.addColorStop(0,'#fff0c8bb');g.addColorStop(.45,'#ffa46566');g.addColorStop(1,'#ff714400');ctx.fillStyle=g;ctx.fillRect(tx-r,ty-r,r*2,r*2);ring(ctx,tx,ty,15+age*.15,'#ffd49a',1-age/750,4);}
 else {const count=e.classId===1&&e.skill===1?5:1;for(let i=0;i<count;i++){const a=angle+(i-(count-1)/2)*.16;const length=e.classId===1&&e.skill===2?500:Math.hypot(tx-e.x,ty-e.y);const x=e.x+Math.cos(a)*length*t,y=e.y-28+Math.sin(a)*length*t;ctx.strokeStyle=e.classId===1?'#d5ffd4':e.color;ctx.lineWidth=e.skill===2?4:2.5;ctx.beginPath();ctx.moveTo(x-Math.cos(a)*40,y-Math.sin(a)*40);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle='#f5ffe9';ctx.beginPath();ctx.arc(x,y,e.classId===1?3:7,0,Math.PI*2);ctx.fill();}}
 for(let i=0;i<12;i++){const a=i*Math.PI/6+e.time,r=12+age*.09;ctx.globalAlpha=1-age/750;ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(e.x+Math.cos(a)*r,e.y-20+Math.sin(a)*r-age*.02,2,0,Math.PI*2);ctx.fill();}}
 else if(e.kind!=='spell'){ring(ctx,e.x,e.y+5,20+age*.06,e.color,alpha);ctx.globalAlpha=alpha;for(let i=0;i<12;i++){const a=i*Math.PI/6;ctx.beginPath();ctx.arc(e.x+Math.cos(a)*age*.06,e.y-20+Math.sin(a)*age*.06-age*.025,2.5,0,Math.PI*2);ctx.fill();}}
 ctx.restore();}}
