import {drawDamageDigits} from './damageSprites';
import {tr} from '../../shared/i18n';
import {BUBBLES,RAIDS} from '../../shared/social';
import {drawTelegraphs,drawEffects} from './effects';
import {animalFrame} from '../../shared/animal-skins';
import {PETS} from '../../shared/pets';
import {MONSTERS,isBoss,NPCS,portalsFor,WORLD,ZONES,groundFor} from '../../shared/content';
import {PositionBuffer,SnapshotTimeline} from './interpolation';
import {sweepMove} from '../../shared/physics';
import {loadArt} from './art';
export {loadArt} from './art';
import type {Snapshot} from '../../shared/types';
export type RenderState={snapshot:Snapshot|null;timeline?:SnapshotTimeline;stepDistance?:number;petPositions?:Map<string,{x:number;y:number;zone:number}>;buffers?:Map<string,PositionBuffer>;bufferStamp?:number;autoPath?:{x:number;y:number}[];keys:Set<string>;camera:{x:number;y:number};local:{x:number;y:number;zone:number};mouse:{x:number;y:number};hoverId?:string;targetId?:string;clockOffset:number;lastSnapshot:number;pendingMove?:{x:number;y:number};correction?:{x:number;y:number};deaths?:Map<string,number>;positions?:Map<string,{x:number;y:number;zone:number;tx?:number;ty?:number;at?:number;vx?:number;vy?:number}>;debug:boolean;volume:number;onEvent?:(kind:string)=>void};
export function drawGame(ctx:CanvasRenderingContext2D,width:number,height:number,state:RenderState,art:Awaited<ReturnType<typeof loadArt>>,dt:number,time:number){const s=state.snapshot;ctx.clearRect(0,0,width,height);if(!s){const scale=Math.max(width/WORLD.w,height/WORLD.h);ctx.drawImage(art.forest,(width-WORLD.w*scale)/2,(height-WORLD.h*scale)/2,WORLD.w*scale,WORLD.h*scale);return;}
 const p=s.player,now=time+state.clockOffset;
 if(state.local.zone!==p.zone){state.local={x:p.x,y:p.y,zone:p.zone};state.camera={x:p.x,y:p.y};state.pendingMove={x:0,y:0};state.correction={x:0,y:0};state.positions?.clear();state.buffers?.clear();state.bufferStamp=undefined;state.timeline=undefined;}
 const input=!(document.activeElement instanceof HTMLInputElement||document.activeElement instanceof HTMLTextAreaElement);let dx=input?Number(state.keys.has('d')||state.keys.has('arrowright'))-Number(state.keys.has('a')||state.keys.has('arrowleft')):0,dy=input?Number(state.keys.has('s')||state.keys.has('arrowdown'))-Number(state.keys.has('w')||state.keys.has('arrowup')):0;

 if(state.autoPath?.length){if(dx||dy)state.autoPath=[];else {while(state.autoPath.length&&Math.hypot(state.autoPath[0].x-state.local.x,state.autoPath[0].y-state.local.y)<8)state.autoPath.shift();const goal=state.autoPath[0];if(goal){const d=Math.hypot(goal.x-state.local.x,goal.y-state.local.y);dx=(goal.x-state.local.x)/Math.max(1,d);dy=(goal.y-state.local.y)/Math.max(1,d);}}}
 if(p.hp>0&&time-state.lastSnapshot<5000){const l=Math.max(1,Math.hypot(dx,dy)),before={x:state.local.x,y:state.local.y};sweepMove(state.local,dx/l*WORLD.speed*dt,dy/l*WORLD.speed*dt);state.pendingMove??={x:0,y:0};const traveled=Math.hypot(state.local.x-before.x,state.local.y-before.y);state.stepDistance=(state.stepDistance||0)+traveled;if(state.stepDistance>=52){state.stepDistance=0;state.onEvent?.('step-'+(ZONES[p.zone]?.safe?3:ZONES[p.zone]?.raid?2:ZONES[p.zone].biome));}state.pendingMove.x+=state.local.x-before.x;state.pendingMove.y+=state.local.y-before.y;}
 if(state.correction){const t=Math.min(1,dt*7);state.local.x+=state.correction.x*t;state.local.y+=state.correction.y*t;state.correction.x*=1-t;state.correction.y*=1-t;}
 const zoom=Math.min(1.05,Math.max(.63,width/1300));const vw=width/zoom,vh=height/zoom;const targetX=Math.max(vw/2,Math.min(WORLD.w-vw/2,state.local.x)),targetY=Math.max(vh/2,Math.min(WORLD.h-vh/2,state.local.y));state.camera.x+=(targetX-state.camera.x)*Math.min(1,dt*5);state.camera.y+=(targetY-state.camera.y)*Math.min(1,dt*5);
 let ox=width/2-state.camera.x*zoom,oy=height/2-state.camera.y*zoom;if(s.events.some(e=>e.kind==='spell'&&e.skill===3&&now-e.time<180)){ox+=Math.sin(time*.075)*3;oy+=Math.cos(time*.08)*3;}
 ctx.save();ctx.translate(ox,oy);ctx.scale(zoom,zoom);ctx.filter=ZONES[p.zone].filter;ctx.drawImage(art.plazas?.[p.zone]||(ZONES[p.zone]?.raid?art.raid:art.biomes?.[ZONES[p.zone].biome]||art.forest),0,0,WORLD.w,WORLD.h);ctx.filter='none';
 // Geometric light, particles and portal effects are rendered independently of scene artwork.
 for(let n=0;n<45;n++){const x=(n*131+Math.sin(time/4000+n)*24)%WORLD.w,y=(n*191-time/150)%WORLD.h;ctx.fillStyle=`rgba(211,255,205,${.16+Math.sin(time/700+n)*.12})`;ctx.beginPath();ctx.arc(x,(y+WORLD.h)%WORLD.h,n%3===0?2:1.2,0,Math.PI*2);ctx.fill();}
 const text=(label:string,x:number,y:number,color='#eff5e8',size=14,authored=true)=>{if(authored)label=tr(label);ctx.font=`600 ${size}px "Noto Sans KR",sans-serif`;ctx.textAlign='center';ctx.lineWidth=4;ctx.strokeStyle='rgba(10,27,28,.88)';ctx.strokeText(label,x,y);ctx.fillStyle=color;ctx.fillText(label,x,y);};
 const portals=portalsFor(p.zone);for(let i=0;i<portals.length;i++){const a=portals[i];const locked=a.target>=0&&p.level<ZONES[a.target].minLevel;const color=locked?'#d09898':a.target===-1?'#e5ccff':a.next===1?'#b9efcf':'#bcdfff';const g=ctx.createRadialGradient(a.x,a.y,3,a.x,a.y,80);g.addColorStop(0,color+'88');g.addColorStop(1,color+'00');ctx.fillStyle=g;ctx.fillRect(a.x-80,a.y-80,160,160);ctx.save();ctx.translate(a.x,a.y-26);ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,23+Math.sin(time/350)*2,0,Math.PI*2);ctx.stroke();ctx.fillStyle=color+'55';ctx.fill();ctx.translate(0,26);ctx.scale(1,.45);ctx.rotate(time/2200);ctx.setLineDash([8,14]);ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,58,0,Math.PI*2);ctx.stroke();ctx.restore();text(a.name+(locked?` · LV.${ZONES[a.target].minLevel}`:''),a.x,a.y-63,color);if(Math.hypot(state.local.x-a.x,state.local.y-a.y)<160)text(a.target===-1?'E / M · 월드 이동':'E · 이동',a.x,a.y+30,'#fff0b6',15);}
 drawTelegraphs(ctx,s,now);
 for(const loot of s.loot){const pulse=Math.sin(time/180)*.3+.6;ctx.shadowColor='#ffda81';ctx.shadowBlur=15;ctx.fillStyle=`rgba(255,220,135,${pulse})`;ctx.beginPath();ctx.moveTo(loot.x,loot.y-12);ctx.lineTo(loot.x+8,loot.y);ctx.lineTo(loot.x,loot.y+12);ctx.lineTo(loot.x-8,loot.y);ctx.closePath();ctx.fill();ctx.shadowBlur=0;text(loot.item!==null?'장비 · 골드':'골드',loot.x,loot.y+29,'#ffe1a4',12);}
 const entities:{x:number;y:number;sprite:number;name:string;kind:string;hp?:number;maxHp?:number;id?:string;hit?:number;face?:number;attackAt?:number;moving?:boolean;deadAt?:number;freezeUntil?:number;stunUntil?:number;burnUntil?:number;gmSkin?:number;animalSkinId?:number}[]=[];
 for(const n of NPCS.filter(n=>n.zone===p.zone))entities.push({...n,kind:'npc',name:n.name,id:'npc-'+n.id});
 state.deaths??=new Map();for(const m of s.monsters){if(m.hp<=0){if(!state.deaths.has(m.id))state.deaths.set(m.id,now);if(now-state.deaths.get(m.id)!>900)continue;}else state.deaths.delete(m.id);entities.push({...m,sprite:ZONES[m.zone]?.raid?RAIDS[m.zone-25].sprite:MONSTERS[m.type].sprite,name:ZONES[m.zone]?.raid?RAIDS[m.zone-25].name:MONSTERS[m.type].name,kind:isBoss(m.type)?'boss':'monster',hit:m.lastHit,attackAt:m.lastAtk,deadAt:state.deaths.get(m.id)});}
 for(const other of s.players)entities.push({...other,sprite:other.classId,name:((other.gmTitle||other.cashTitle)?'['+(other.gmTitle||other.cashTitle)+'] ':'')+other.name,kind:'other'});
 entities.push({x:state.local.x,y:state.local.y,sprite:p.classId,gmSkin:p.gmSkin,animalSkinId:p.animalSkinId,name:((p.gmTitle||p.cashTitle)?'['+(p.gmTitle||p.cashTitle)+'] ':'')+p.name,kind:'player',hp:p.hp,id:p.id,face:dx?dx>0?1:-1:p.face,attackAt:p.attackAt});state.buffers??=new Map();state.positions??=new Map();state.timeline??=new SnapshotTimeline();const fresh=state.bufferStamp!==s.now;if(fresh)state.timeline.add(s.now,time);const playback=state.timeline.at(time);for(const e of entities){if(e.kind==='player'||e.kind==='npc')continue;const id=e.id!;let buffer=state.buffers.get(id);if(!buffer){buffer=new PositionBuffer();state.buffers.set(id,buffer);}if(fresh)buffer.add(s.now,e.x,e.y);const frozen=e.hp===0||(e.freezeUntil||0)>now||(e.stunUntil||0)>now;const sample=buffer.at(playback,frozen?0:180);if(sample){let shown=state.positions.get(id);if(!shown||Math.hypot(shown.x-sample.x,shown.y-sample.y)>250)shown={x:sample.x,y:sample.y,zone:p.zone};const blend=1-Math.exp(-dt*22);shown.x+=(sample.x-shown.x)*blend;shown.y+=(sample.y-shown.y)*blend;state.positions.set(id,shown);e.x=shown.x;e.y=shown.y;e.moving=!frozen&&sample.moving;e.face=sample.face;}}state.bufferStamp=s.now;const visible=new Set(entities.map(e=>e.id));for(const id of state.buffers.keys())if(!visible.has(id)){state.buffers.delete(id);state.positions.delete(id);}entities.sort((a,b)=>a.y-b.y);
 for(const e of entities){const large=e.kind==='boss',size=large?140:e.kind==='monster'?88:e.kind==='npc'?114:105;const walking=e.kind==='player'?(dx||dy):e.moving,bounce=walking?Math.sin(time/(e.kind==='player'||e.kind==='other'?90:160))*(e.kind==='player'||e.kind==='other'?3:1.5):e.kind==='monster'?Math.sin(time/500+e.x*.01)*1:Math.sin(time/700+e.x)*1.3;
 if(e.id===state.hoverId||e.id===state.targetId){ctx.strokeStyle=e.kind==='npc'?'#ffe1a2':'#f5c797';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y+5,size*.3,13,0,0,Math.PI*2);ctx.stroke();}
 if((e.freezeUntil||0)>now||(e.stunUntil||0)>now){ctx.strokeStyle='#baf3ff';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.x,e.y-20,35,45,0,0,Math.PI*2);ctx.stroke();text((e.freezeUntil||0)>now?'빙결':'기절',e.x,e.y+35,'#c7eeff',12);}
 if((e.burnUntil||0)>now){ctx.fillStyle='#ffc073';for(let i=0;i<5;i++){ctx.globalAlpha=.5+Math.sin(time/160+i)*.3;ctx.beginPath();ctx.arc(e.x+Math.sin(i*4)*20,e.y-20-((time/20+i*11)%55),2.5,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
 ctx.fillStyle='rgba(10,30,30,.28)';ctx.beginPath();ctx.ellipse(e.x,e.y+5,size*.26,9,0,0,Math.PI*2);ctx.fill();if(e.kind==='player'){ctx.strokeStyle='#d2e7b8aa';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(e.x,e.y+5,29,12,0,0,Math.PI*2);ctx.stroke();}
 const age=e.attackAt?now-e.attackAt:Infinity;ctx.save();ctx.translate(e.x,e.y+bounce);if(e.face===-1)ctx.scale(-1,1);if(age<260)ctx.rotate(Math.sin(age/260*Math.PI)*.13);if(e.hp===0){if(!state.deaths.has(e.id!))state.deaths.set(e.id!,now);e.deadAt=state.deaths.get(e.id!);ctx.globalAlpha=e.kind==='monster'||large?Math.max(0,1-(now-e.deadAt!)/900):.8;}else if(e.kind==='player'||e.kind==='other')state.deaths.delete(e.id!);if(e.kind==='player'&&(p.dodgeUntil||0)>now){ctx.globalAlpha=.6;ctx.shadowColor='#b4e3ff';ctx.shadowBlur=18;}if(e.hit&&now-e.hit<130)ctx.filter='brightness(2.4)';const frames=e.sprite<3?art.animations?.[e.sprite]:undefined;const motion=art.monsterAnimations[e.sprite];
 const phase=(e.id||'').split('').reduce((a,c)=>a+c.charCodeAt(0),0)*31;
 const animated=motion&&e.hp!==0&&((e.freezeUntil||0)<=now&&(e.stunUntil||0)<=now);
 let frame=motion?motion[animated?(e.sprite===11||e.sprite===23||walking||age<400?Math.floor((time+phase)/(e.sprite===11?145:e.sprite===24?125:170))%4:0):0]:art.sprites[e.sprite];if(frames){const row=e.hp===0?2:age<520?1:walking?0:-1;if(row>=0){const index=row===2?Math.min(3,Math.floor((now-(e.deadAt||now))/180)):row===1?Math.min(3,Math.floor(age/130)):Math.floor(time/120)%4;frame=frames[row*4+index];}}const animal=art.animalAnimations[e.gmSkin??e.animalSkinId??-1];if(animal&&(e.kind==='player'||e.kind==='other'))frame=animal[animalFrame({dead:e.hp===0,deathAge:now-(e.deadAt??now),attackAge:age,moving:!!walking,time})];if(motion&&e.sprite>=25){const index=e.hp===0?3:age>=0&&age<520?2:animated&&walking?Math.floor((time+phase)/170)%2:0;frame=motion[index];}ctx.drawImage(frame,-size/2,-size+18,size,size);ctx.shadowBlur=0;ctx.restore();text(e.kind==='player'||e.kind==='other'?e.name:tr(e.name),e.x,e.y-size+7,e.kind==='player'?'#fff3c4':e.kind==='npc'?'#e6d395':large?'#ffc5ba':'#f1f1df',large?15:13,e.kind!=='player'&&e.kind!=='other');
 if(e.kind==='monster'||large){ctx.fillStyle='#17312deb';ctx.fillRect(e.x-25,e.y-size+16,50,5);ctx.fillStyle=large?'#e9907f':'#baed96';ctx.fillRect(e.x-25,e.y-size+16,50*(e.hp||0)/(e.maxHp||1),5);}
 if(e.kind==='npc'){const n=NPCS.find(n=>'npc-'+n.id===e.id)!;text(n.role,e.x,e.y+29,'#cfdbc4',12);if(Math.hypot(e.x-state.local.x,e.y-state.local.y)<160)text('E · 대화',e.x,e.y+49,'#fff0b6',14);}
 }
 state.petPositions??=new Map();for(const owner of [p,...s.players]){const petId=owner.petId;if(petId===undefined||petId===null||!owner.pets?.includes(petId)||owner.hp<=0)continue;const leader=owner.id===p.id?state.local:owner,target={x:leader.x-42*(owner.face||1),y:leader.y+24};let pet=state.petPositions.get(owner.id);if(!pet||pet.zone!==p.zone||Math.hypot(pet.x-target.x,pet.y-target.y)>350)pet={...target,zone:p.zone};const moving=Math.hypot(pet.x-target.x,pet.y-target.y)>5;pet.x+=(target.x-pet.x)*Math.min(1,dt*6);pet.y+=(target.y-pet.y)*Math.min(1,dt*6);state.petPositions.set(owner.id,pet);const frame=art.pets?.[petId]?.[moving||petId===1?Math.floor(time/150)%4:0];if(!frame)continue;ctx.save();ctx.translate(pet.x,pet.y+(petId===1?-16+Math.sin(time/380)*3:0));if(owner.face===-1)ctx.scale(-1,1);ctx.fillStyle='rgba(10,25,28,.25)';ctx.beginPath();ctx.ellipse(0,8,18,6,0,0,Math.PI*2);ctx.fill();ctx.drawImage(frame,-35,-60,70,70);ctx.restore();if(owner.id===p.id)text(PETS[petId].name,pet.x,pet.y+25,'#e1d2ab',10);}
 // Draw the latest bubble above each interpolated player. Text remains live and wraps in Korean.
 for(const owner of [p,...s.players]){const chat=s.chat.filter(c=>c.zone===p.zone&&(c.playerId===owner.id||c.id.startsWith(owner.id+':'))&&now-c.time<7000).at(-1);if(!chat)continue;const e=entities.find(e=>e.id===owner.id);if(!e)continue;const style=BUBBLES[owner.bubbleId||0]||BUBBLES[0];ctx.font='500 14px "Noto Sans KR",sans-serif';const lines:string[]=[];let line='';for(const ch of chat.text){if(ctx.measureText(line+ch).width>218){lines.push(line);line='';}line+=ch;}if(line)lines.push(line);if(lines.length>4){lines.length=4;lines[3]=lines[3].slice(0,-1)+'…';}const w=Math.max(90,...lines.map(l=>ctx.measureText(l).width))+36,h=lines.length*21+24,x=Math.max(w/2+12,Math.min(WORLD.w-w/2-12,e.x)),y=e.y-126-h;ctx.save();ctx.globalAlpha=Math.min(1,(7000-(now-chat.time))/450);ctx.shadowColor='#0006';ctx.shadowBlur=10;ctx.fillStyle=style.fill;ctx.strokeStyle=style.border;ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(x-w/2,y,w,h,owner.bubbleId===10?5:14);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.beginPath();ctx.moveTo(x-8,y+h);ctx.lineTo(e.x,y+h+12);ctx.lineTo(x+8,y+h);ctx.fill();ctx.stroke();ctx.fillStyle=style.fill;ctx.fillRect(x-7,y+h-2,14,4);ctx.fillStyle=style.border;ctx.textAlign='center';ctx.font='17px serif';ctx.fillText(style.glyph,x-w/2+5,y+6);ctx.fillText(style.glyph,x+w/2-5,y+6);ctx.fillStyle=[7,10,13,15].includes(style.id)?'#fff3dc':'#2b3442';ctx.font='500 14px "Noto Sans KR",sans-serif';lines.forEach((l,i)=>ctx.fillText(l,x,y+23+i*21));ctx.restore();}
 drawEffects(ctx,s,now);
 for(const e of s.events){const age=now-e.time;if(age<0||age>1500)continue;const progress=age/1500;if(e.kind==='hit'||e.kind==='heal'){ctx.globalAlpha=1-progress;const dx=e.x+Math.sin(e.time)*15,dy=e.y-65-age*.045;if(e.kind!=='hit'||e.effect==='player-hurt'||!drawDamageDigits(ctx,e.value,e.damageSkinId||0,dx,dy,e.critical?42:34))text((e.kind==='heal'?'+':'')+e.value,dx,dy,e.color,e.critical?27:e.value>50?23:19);if(e.critical)text('CRITICAL',e.x,e.y-90-age*.045,'#ffe7a4',12);ctx.globalAlpha=1;}if(e.kind==='level'){ctx.globalAlpha=1-progress;text('LEVEL UP',e.x,e.y-120-progress*30,'#ffe4a2',24);ctx.globalAlpha=1;}}
 if(state.debug){ctx.strokeStyle='#ff6666';ctx.beginPath();groundFor(p.zone).forEach((point,i)=>{if(i===0)ctx.moveTo(point.x,point.y);else ctx.lineTo(point.x,point.y);});ctx.closePath();ctx.stroke();text(`x ${Math.round(state.local.x)} · y ${Math.round(state.local.y)} · ${Math.round(1/dt)} FPS`,state.local.x,state.local.y+75,'#fff',14);}
 ctx.restore();const vignette=ctx.createRadialGradient(width/2,height/2,height*.18,width/2,height/2,Math.max(width,height)*.65);vignette.addColorStop(0,'rgba(3,17,22,0)');vignette.addColorStop(1,'rgba(3,17,22,.65)');ctx.fillStyle=vignette;ctx.fillRect(0,0,width,height);
}
