import { tr } from '../../shared/i18n';
import { useState } from 'react';
import { Map, Lock, Sparkles } from 'lucide-react';
import { ZONES } from '../../shared/content';
import type { Player } from '../../shared/types';
export default function WorldMap({ player, onTravel }: {
    player: Player;
    onTravel: (zone: number) => void;
}) { const [hover, setHover] = useState(player.zone); return <div className="world-map-panel"><div className="world-map-info"><Map size={18}/><strong>{tr("에테리아 · 별의 대륙")}</strong><span>LV. {player.level}</span></div><p>{tr("지도 위 지역을 클릭하면 이동합니다. 입장 레벨이 부족한 지역은 잠겨 있습니다. 광장은 차원문 없이 바로 이동합니다.")}</p><div className="town-shortcuts" aria-label={tr("광장 목록")}>{ZONES.filter(z => z.safe).map(z => <button key={z.id} disabled={player.level < z.minLevel || player.zone === z.id} onClick={() => onTravel(z.id)}>{tr(z.name)}<small>{tr(player.zone === z.id ? '현재 광장' : player.level < z.minLevel ? `LV. ${z.minLevel} 필요` : '바로 이동')}</small></button>)}</div><div className="region-list" aria-label={tr('지역 선택')}>{ZONES.filter(z=>!z.raid).map(z=><button type="button" key={z.id} className={z.id===player.zone?'current':''} disabled={player.level<z.minLevel||z.id===player.zone||player.hp<=0} onClick={()=>onTravel(z.id)}><strong>{tr(z.name)}</strong><small>{tr(z.id===player.zone?'현재 위치':player.level<z.minLevel?'LV. '+z.minLevel+' 필요':z.safe?'안전 지역':'LV. '+z.minLevel+' · 이동')}</small></button>)}</div><div className="atlas-scroll"><div className="world-atlas"><img src="/art/world-atlas.png" alt={tr("서쪽의 푸른 숲, 북쪽 설원, 동쪽 불의 대륙과 남쪽 별의 섬으로 이어지는 에테리아 세계지도")}/>{ZONES.filter(z => !z.raid).map(z => { const locked = player.level < z.minLevel, current = z.id === player.zone; return <button key={z.id} className={'atlas-location biome-' + z.biome + (current ? ' current' : '') + (locked ? ' locked' : '')} style={{ left: `${z.mapX}%`, top: `${z.mapY}%` }} disabled={locked || current} onMouseEnter={() => setHover(z.id)} onFocus={() => setHover(z.id)} onClick={() => onTravel(z.id)} aria-label={tr(`${z.name}, ${z.safe ? '안전 지역' : `입장 레벨 ${z.minLevel}`}${current ? ', 현재 위치' : locked ? ', 잠김' : ''}`)} title={tr(z.sub)}><span className="atlas-orb">{locked ? <Lock size={13}/> : z.id + 1}</span><strong>{tr(z.name)}</strong><small>{tr(current ? '현재 위치' : z.safe ? 'SAFE' : `LV. ${z.minLevel}+`)}</small></button>; })}</div></div><div className="map-legend"><Sparkles size={17}/>{tr(ZONES[hover].name)} · {tr(ZONES[hover].level)} · {tr(ZONES[hover].sub)}</div></div>; }

