import {createRequire} from 'node:module';import {realpathSync,mkdirSync} from 'node:fs';import {resolve} from 'node:path';import assert from 'node:assert/strict';import {startGm} from '../gm/server.mjs';
const req=createRequire(realpathSync('node_modules/wrangler/package.json')),{Miniflare}=req('miniflare'),token='test-gm-token-'+ 'a'.repeat(64);let mf,app;
const options={modules:true,scriptPath:resolve('dist/external/server/worker.js'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],bindings:{GM_TOKEN:token},durableObjects:{REALM:{className:'AetheriaRealm',useSQLite:true}},durableObjectsPersist:resolve('.sites-runtime/gm-test-world'),assets:{directory:resolve('dist/external/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:true,has_user_worker:true}}};
const origin='http://localhost',headers={'Content-Type':'application/json',Origin:origin};
async function call(path,body,cookie,admin=false){const r=await mf.dispatchFetch(origin+path,{method:body?'POST':'GET',headers:{...headers,...(cookie?{Cookie:cookie}:{}),...(admin?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
try{mf=new Miniflare(options);assert.equal((await call('/api/gm/players')).status,401);const user=await call('/api/account'),c=await call('/api/account',{action:'create',name:'GM검증',classId:0},user.cookie),id=c.data.active;
 const r=await mf.dispatchFetch(origin+'/api/socket?characterId='+id,{headers:{Cookie:user.cookie,Origin:origin,Upgrade:'websocket'}}),ws=r.webSocket;ws.accept();const push=new Promise((ok,no)=>{const timer=setTimeout(()=>no(new Error('GM live push timed out')),3000);ws.addEventListener('message',e=>{const s=JSON.parse(e.data);if(s.player?.level===20&&s.player?.gold===900){clearTimeout(timer);ok(s);}});});
 let detail=(await call('/api/gm/player?id='+id,null,null,true)).data;assert.equal((await call('/api/gm/action',{playerId:id,revision:detail.revision,action:'set',level:20,gold:900},null,true)).status,200);const updated=await push;assert.equal(updated.player.level,20);assert.equal(updated.player.gold,900);
 assert.equal((await call('/api/gm/action',{playerId:id,revision:detail.revision,action:'addGold',amount:100},null,true)).status,409);detail=(await call('/api/gm/player?id='+id,null,null,true)).data;
 await call('/api/gm/action',{playerId:id,revision:detail.revision,action:'giveItem',itemId:14,quantity:2},null,true);assert.equal((await call('/api/game?characterId='+id,null,user.cookie)).data.player.inventory.filter(i=>i===14).length,2);
 await call('/api/gm/settings',{donationGuide:'실제 후원 확인 테스트',donationUrl:'https://example.org/donate'},null,true);const request=await call('/api/game?characterId='+id,{seq:100,action:'donationRequest',value:1,reference:'후원 확인검증'},user.cookie);const donation=request.data.donations.at(-1);assert.equal(request.data.player.cash,undefined);assert.equal((await call('/api/gm/donation',{id:donation.id,revision:0,approve:true,confirmReceived:true},user.cookie)).status,401);assert.equal((await call('/api/gm/donation',{id:donation.id,revision:0,approve:true,confirmReceived:true},null,true)).status,200);assert.equal((await call('/api/gm/donation',{id:donation.id,revision:0,approve:true,confirmReceived:true},null,true)).status,400);const bought=await call('/api/game?characterId='+id,{seq:101,action:'cashBuy',value:0},user.cookie);assert.equal(bought.data.player.cash,300);assert.ok(bought.data.player.bubbles.includes(12));
 detail=(await call('/api/gm/player?id='+id,null,null,true)).data;
 const cashPush=new Promise((ok,no)=>{const timer=setTimeout(()=>no(new Error('GM cash live push timed out')),3000);ws.addEventListener('message',e=>{const snap=JSON.parse(e.data);if(snap.player?.cash===450){clearTimeout(timer);ok(snap);}});});
 assert.equal((await call('/api/gm/action',{playerId:id,revision:detail.revision,action:'addCash',amount:150,reason:'코인 지급 검증'},null,true)).status,200);await cashPush;
 detail=(await call('/api/gm/player?id='+id,null,null,true)).data;assert.equal(detail.cash,450);assert.equal((await call('/api/gm/action',{playerId:id,revision:detail.revision,action:'addCash',amount:-150,reason:'검증 지급 회수'},null,true)).status,200);console.log('PASS: GM cash grant broadcasts live, withdrawal and audited persistence');
 const automated=await call('/api/game?characterId='+id,{seq:102,action:'autoSkillMode',value:2},user.cookie);assert.equal(automated.data.player.autoSkillMode,2);assert.ok(automated.data.player.skillRanks.reduce((a,b)=>a+b,0)>0);
 const world=(await call('/api/gm/backup',null,null,true)).data;assert.ok(!JSON.stringify(world).includes(token));assert.ok((await call('/api/gm/audit',null,null,true)).data.entries.some(e=>e.action==='donationApprove'));
 console.log('PASS: GM auth, live WebSocket change, stale revision rejection, item grant, donation approval gate and cash shop');
 detail=(await call('/api/gm/player?id='+id,null,null,true)).data;await call('/api/gm/action',{playerId:id,revision:detail.revision,action:'ban'},null,true);assert.equal((await call('/api/game?characterId='+id,null,user.cookie)).status,403);detail=(await call('/api/gm/player?id='+id,null,null,true)).data;await call('/api/gm/action',{playerId:id,revision:detail.revision,action:'unban'},null,true);assert.equal((await call('/api/game?characterId='+id,null,user.cookie)).status,200);
 ws.close();await new Promise(r=>setTimeout(r,100));await mf.dispose();mf=new Miniflare(options);const restored=(await call('/api/gm/player?id='+id,null,null,true)).data;assert.equal(restored.gold,900);assert.equal(restored.cash,300);assert.equal(restored.level,20);const savedSkills=(await call('/api/game?characterId='+id,null,user.cookie)).data.player;assert.equal(savedSkills.autoSkillMode,2);assert.ok(savedSkills.skillRanks.reduce((a,b)=>a+b,0)>0);console.log('PASS: GM, cash and automatic skill settings persist across actual server restart');
 await mf.ready;const remote=await mf.ready;app=await startGm({port:0,quiet:true,config:{url:remote.origin,token,loginCode:'TEST-PRIVATE-LOGIN-CODE'}});const gmOrigin='http://127.0.0.1:'+app.address().port;
 const proxy=async(path,body,cookie,originOverride)=>{const r=await fetch(gmOrigin+path,{method:body?'POST':'GET',headers:{Origin:originOverride||gmOrigin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 assert.equal((await proxy('/api/players')).status,401);assert.equal((await proxy('/api/login',{code:'bad'})).status,401);const login=await proxy('/api/login',{code:'TEST-PRIVATE-LOGIN-CODE'});assert.equal(login.status,200);assert.ok(login.cookie);assert.equal((await proxy('/api/players',null,login.cookie)).status,200);assert.equal((await proxy('/api/action',{playerId:id,revision:restored.revision,action:'addGold',amount:10},login.cookie,'https://attacker.test')).status,403);const mutation=await proxy('/api/action',{playerId:id,revision:restored.revision,action:'addGold',amount:10},login.cookie);assert.equal(mutation.status,200);assert.equal(mutation.data.player.gold,910);assert.equal((await proxy('/api/logout',{},login.cookie)).status,200);assert.equal((await proxy('/api/players',null,login.cookie)).status,401);
 const page=await fetch(gmOrigin);assert.equal(page.status,200);assert.ok(!(await page.text()).includes(token));console.log('PASS: separate GM program login, session proxy, logout, CSRF protection and secret isolation');
}finally{if(app)await new Promise(r=>app.close(r));if(mf)await mf.dispose();}
