import {createRequire} from 'node:module';
import {readFileSync,realpathSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(realpathSync(new URL('../node_modules/wrangler/package.json',import.meta.url)));
const {Miniflare}=require('miniflare');
const root=resolve('dist/server');const files=readdirSync(root,{recursive:true}).filter(f=>f.endsWith('.js'));const modules=['index.js',...files.filter(f=>f!=='index.js')].map(f=>({type:'ESModule',path:resolve(root,f)}));
const mf=new Miniflare({modules,modulesRoot:root,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'aetheria-integration'},assets:{directory:resolve('dist/client'),binding:'ASSETS',routerConfig:{invoke_user_worker_ahead_of_assets:true,has_user_worker:true}}});
const origin='https://aetheria.test';
try{
 const db=await mf.getD1Database('DB');
 const migration=readFileSync('drizzle/0000_talented_epoch.sql','utf8');for(const sql of migration.split('--> statement-breakpoint'))await db.exec(sql.trim().replace(/\n/g,' '));
 const home=await mf.dispatchFetch(origin);assert.equal(home.status,200);const html=await home.text();assert.ok(html.includes('수호자 선택')&&html.includes('진행 정보 확인 중'));console.log('PASS: rendered home page and Korean character creation');
 const api=async(cookie,body)=>{const r=await mf.dispatchFetch(origin+'/api/game',{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Origin:origin,...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return {r,data:await r.json()};};
 const a=await api(null,{join:true,name:'검증기사',classId:0});assert.equal(a.r.status,200);const ac=a.r.headers.get('set-cookie').split(';')[0];assert.equal(a.data.player.name,'검증기사');
 const b=await api(null,{join:true,name:'검증마도사',classId:2});const bc=b.r.headers.get('set-cookie').split(';')[0];assert.notEqual(a.data.player.id,b.data.player.id);console.log('PASS: two independent guest characters');
 let time=Date.now();const wait=()=>new Promise(r=>setTimeout(r,125));await wait();const state=await api(ac,{seq:1,dx:1,dy:0});assert.ok(state.data.player.x>a.data.player.x);assert.ok(state.data.players.some(p=>p.name==='검증마도사'));const other=await api(bc);assert.ok(other.data.players.some(p=>p.name==='검증기사'&&p.x===state.data.player.x));console.log('PASS: authoritative movement visible to second player');
 const saved=await api(ac);assert.equal(saved.data.player.x,state.data.player.x);assert.equal(saved.data.player.gold,state.data.player.gold);console.log('PASS: progress reload from durable database');
 const upgrade=await mf.dispatchFetch(origin+'/api/socket',{headers:{Upgrade:'websocket',Cookie:ac,Origin:origin}});assert.equal(upgrade.status,101);const ws=upgrade.webSocket;ws.accept();await wait();const reply=new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('WebSocket timeout')),6000);ws.addEventListener('message',e=>{clearTimeout(t);resolve(JSON.parse(e.data));},{once:true});});ws.send(JSON.stringify({seq:2,dx:0,dy:1}));const message=await reply;assert.equal(message.player.lastSeq,2);assert.ok(message.players.some(p=>p.name==='검증마도사'));ws.close();console.log('PASS: real WebSocket input and multiplayer snapshot');
 const forbidden=await mf.dispatchFetch(origin+'/api/socket',{headers:{Upgrade:'websocket',Cookie:ac,Origin:'https://evil.test'}});assert.equal(forbidden.status,403);const missing=await mf.dispatchFetch(origin+'/api/socket',{headers:{Upgrade:'websocket',Origin:origin}});assert.equal(missing.status,401);console.log('PASS: WebSocket guest authentication and origin validation');
 // Apply a late acknowledgement replay: gold-changing actions must not execute twice.
 await wait();const seq2=await api(ac,{seq:2,dx:1,dy:1});assert.equal(seq2.data.player.lastSeq,2);assert.equal(seq2.data.player.y,message.player.y);console.log('PASS: duplicate sequence reconciliation');

 const aid=a.data.player.id;let sequence=2;
 const fixture=async(fn)=>{const row=await db.prepare('SELECT data FROM realms WHERE id = ?').bind('aetheria').first();const world=JSON.parse(row.data);fn(world,world.players[aid]);world.players[aid].last=Date.now()-1000;world.players[aid].seen=Date.now();await db.prepare('UPDATE realms SET data = ?, version = version + 1 WHERE id = ?').bind(JSON.stringify(world),'aetheria').run();};
 const action=async(body)=>{const result=await api(ac,{seq:++sequence,...body});assert.equal(result.r.status,200);return result.data;};
 await fixture((w,p)=>{p.zone=0;p.x=830;p.y=560;});const quest=await action({action:'quest',value:0});assert.equal(quest.player.quests[0],0);
 await fixture((w,p)=>{p.x=1530;p.y=680;});const portal=await action({action:'portal',value:0});assert.equal(portal.player.zone,1);
 for(let i=0;i<5;i++){let target;await fixture((w,p)=>{p.x=520;p.y=420;p.zone=1;p.cd[0]=0;p.hp=200;const m=w.monsters.find(m=>m.type===0&&m.zone===1);m.hp=1;m.deadUntil=0;m.x=550;m.y=420;target={x:m.x,y:m.y};});const battle=await action({skill:0,tx:target.x,ty:target.y});assert.ok(battle.loot.length);}
 const progression=await api(ac);assert.equal(progression.data.player.quests[0],5);assert.equal(progression.data.player.level,1);
 await fixture((w,p)=>{w.loot.push({id:'test-equipment',owner:aid,zone:1,x:p.x,y:p.y,gold:17,item:7,potion:true,expires:Date.now()+60000});});const drop=await action({action:'loot'});assert.ok(drop.player.inventory.includes(7));await fixture(()=>{});const equipped=await action({action:'equip',value:7});assert.equal(equipped.player.equipment.weapon,7);
 await fixture((w,p)=>{p.x=270;p.y=680;});const back=await action({action:'portal',value:1});assert.equal(back.player.zone,0);await fixture((w,p)=>{p.x=830;p.y=560;});const rewarded=await action({action:'quest',value:0});assert.ok(rewarded.player.done.includes(0));assert.ok(rewarded.player.level>=2);const reload=await api(ac);assert.deepEqual(reload.data.player.equipment,rewarded.player.equipment);assert.deepEqual(reload.data.player.done,[0]);console.log('PASS: full first quest loop, portal travel, five kills, level-up, loot, equipment, reward and reload');
 await fixture(()=>{});const trained=await action({action:'train',value:0});assert.equal(trained.player.skillRanks[0],1);const trainedReload=await api(ac);assert.equal(trainedReload.data.player.skillRanks[0],1);await fixture(()=>{});const dodged=await action({action:'dodge',tx:1500,ty:560});assert.ok(dodged.player.dodgeCd>dodged.now);assert.ok(dodged.player.dodgeUntil>dodged.now);console.log('PASS: skill mastery persists and authoritative dodge works through production API');
 await fixture((w,p)=>{p.level=5;p.skillRanks=Array(8).fill(0);});const unlocked=await action({action:'train',value:4});assert.equal(unlocked.player.skillRanks[4],1);const bound=await action({action:'bind',slot:2,value:4});assert.equal(bound.player.loadout[2],4);const boundReload=await api(ac);assert.equal(boundReload.data.player.loadout[2],4);const removed=await action({action:'bind',slot:2,value:-1});assert.equal(removed.player.loadout[2],-1);await fixture((w,p)=>{p.zone=0;p.x=900;p.y=925;});const denied=await action({action:'travel',value:24});assert.equal(denied.player.zone,0);assert.ok(denied.player.notice.includes('49'));await fixture((w,p)=>{p.level=49;});const fastTravel=await action({action:'travel',value:24});assert.equal(fastTravel.player.zone,24);await fixture((w,p)=>{p.x=700;p.y=600;});const delta=await action({dx:0,dy:0,moveX:100,moveY:0});assert.ok(Math.abs(delta.player.x-800)<.01);console.log('PASS: advanced skill learning, assign/remove persistence, orb level gates and delta movement through actual API');
 await fixture((w,p)=>{p.zone=0;p.x=830;p.y=560;p.level=10;});const trial=await action({action:'promotion'});assert.equal(trial.player.promotionQuest.tier,1);const refusedPromotion=await action({action:'promotion'});assert.equal(refusedPromotion.player.promotionTier,undefined);await fixture((w,p)=>{p.promotionQuest.kills=10;p.promotionQuest.bosses=1;});const promoted=await action({action:'promotion'});assert.equal(promoted.player.promotionTier,1);const promotionReload=await api(ac);assert.equal(promotionReload.data.player.promotionTier,1);const newSpell=await action({action:'train',value:8});assert.equal(newSpell.player.skillRanks[8],1);const newBinding=await action({action:'bind',slot:1,value:8});assert.equal(newBinding.player.loadout[1],8);console.log('PASS: promotion trial, incomplete rejection, completion persistence and promoted skill binding');
 for(let zone=1;zone<=24;zone++){await fixture((w,p)=>{p.level=50;p.zone=zone-1;p.x=1530;p.y=680;});const transition=await action({action:'portal',value:0});assert.equal(transition.player.zone,zone);assert.ok(transition.monsters.length);if(zone===4)assert.ok(transition.monsters.some(m=>m.type===9));}console.log('PASS: all 25 zones and dungeon boss availability');
 await fixture((w,p)=>{p.hp=0;});const alive=await action({action:'respawn'});assert.equal(alive.player.zone,0);assert.ok(alive.player.hp>0);console.log('PASS: death and respawn with equipment preserved');

 const cookies=[ac,bc];for(let i=0;i<18;i++){const joined=await api(null,{join:true,name:'동시접속'+i,classId:i%3});assert.equal(joined.r.status,200);cookies.push(joined.r.headers.get('set-cookie').split(';')[0]);}
 const sockets=await Promise.all(cookies.map(async cookie=>{const current=await api(cookie);const response=await mf.dispatchFetch(origin+'/api/socket',{headers:{Upgrade:'websocket',Cookie:cookie,Origin:origin}});assert.equal(response.status,101);response.webSocket.accept();return {ws:response.webSocket,seq:current.data.player.lastSeq+1};}));await wait();
 const concurrent=await Promise.all(sockets.map(({ws,seq})=>new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('20-player socket timeout')),8000);ws.addEventListener('message',event=>{clearTimeout(t);const data=JSON.parse(event.data);if(data.error)reject(new Error(data.error));else resolve(data);},{once:true});ws.send(JSON.stringify({seq,dx:1,dy:0}));})));
 assert.equal(concurrent.length,20);for(let i=0;i<20;i++){assert.equal(concurrent[i].player.lastSeq,sockets[i].seq);assert.equal(concurrent[i].online,20);sockets[i].ws.close();}console.log('PASS: 20 simultaneous real WebSocket clients with authoritative movement');
 for(let i=1;i<=8;i++){const audio=await mf.dispatchFetch(origin+`/audio/track-${i}.mp3`);assert.equal(audio.status,200);assert.ok((await audio.arrayBuffer()).byteLength>10000);}for(const name of ['knight-motion','ranger-motion','mage-motion','snow','ember','world-atlas','advanced-skills']){const image=await mf.dispatchFetch(origin+`/art/${name}.png`);assert.equal(image.status,200);}console.log('PASS: all eight music files and five new artwork assets served by production Worker');

 const accountRequest=async(cookie,body)=>{const r=await mf.dispatchFetch(origin+'/api/account',{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});return {r,data:await r.json()};};
 const fresh=await accountRequest(null,{action:'create',name:'새로운수호자',classId:1});assert.equal(fresh.r.status,200);const nc=fresh.r.headers.get('set-cookie').split(';')[0],nid=fresh.data.active;assert.ok(nid);
 const freshGame=await mf.dispatchFetch(origin+'/api/game?characterId='+nid,{headers:{Cookie:nc}});assert.equal((await freshGame.json()).player.id,nid);
 const roster=await accountRequest(nc);assert.equal(roster.data.characters.length,1);
 const stolen=await mf.dispatchFetch(origin+'/api/game?characterId='+nid,{headers:{Cookie:ac}});assert.equal((await stolen.json()).needsCharacter,true);
 const mainAccept=await mf.dispatchFetch(origin+'/api/game?characterId='+nid,{method:'POST',headers:{Cookie:nc,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({seq:1,action:'quest',value:0})});assert.equal((await mainAccept.json()).player.quests[0],0);
 const sideAccept=await mf.dispatchFetch(origin+'/api/game?characterId='+nid,{method:'POST',headers:{Cookie:nc,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({seq:2,action:'quest',value:25})});assert.equal((await sideAccept.json()).player.quests[25],0);
 const stored=await db.prepare('SELECT data FROM realms WHERE id=?').bind('aetheria').first();const world=JSON.parse(stored.data);const np=world.players[nid];np.zone=1;np.x=700;np.y=700;np.quests[25]=4;const beforeGold=np.gold;
 await db.prepare('UPDATE realms SET data=?,version=version+1 WHERE id=?').bind(JSON.stringify(world),'aetheria').run();
 const claim=async(seq)=>{const r=await mf.dispatchFetch(origin+'/api/game?characterId='+nid,{method:'POST',headers:{Cookie:nc,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({seq,action:'quest',value:25})});return r.json();};
 const claimed=await claim(3);assert.ok(claimed.player.done.includes(25));assert.ok(claimed.player.gold>beforeGold);const claimedTwice=await claim(4);assert.equal(claimedTwice.player.gold,claimed.player.gold);
 const chat=await mf.dispatchFetch(origin+'/api/chat?characterId='+nid,{method:'POST',headers:{Cookie:nc,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({text:'새로운 별길에서 만나요!'})});assert.equal(chat.status,200);
 const newSheet=await mf.dispatchFetch(origin+'/art/monster-motion-v13.png');assert.equal(newSheet.status,200);
 console.log('PASS: new character lobby API, ownership checks, remote quest acceptance/reward once, chat, and new sprite assets');

 const chatState=await api(ac);const chatUpgrade=await mf.dispatchFetch(origin+'/api/socket',{headers:{Upgrade:'websocket',Cookie:ac,Origin:origin}});assert.equal(chatUpgrade.status,101);const chatSocket=chatUpgrade.webSocket;chatSocket.accept();
 const chatSequence=chatState.data.player.lastSeq+1;
 const inputAck=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Input/chat timeout')),6000);chatSocket.addEventListener('message',event=>{const packet=JSON.parse(event.data);if(packet.player?.lastSeq===chatSequence){clearTimeout(timer);resolve(packet);}});});
 chatSocket.send(JSON.stringify({seq:chatSequence,dx:0,dy:0}));chatSocket.send(JSON.stringify({kind:'chat',text:'동시채팅테스트'}));await inputAck;await wait();const delivered=await api(ac);assert.ok(delivered.data.chat.some(message=>message.text==='동시채팅테스트'),'chat survives a concurrent gameplay request');
 const limited=await mf.dispatchFetch(origin+'/api/chat',{method:'POST',headers:{Cookie:ac,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({text:'너무빠른채팅'})});assert.equal(limited.status,429,'throttled chat reports failure instead of silently dropping the draft');chatSocket.close();
 const ownedUpgrade=await mf.dispatchFetch(origin+'/api/socket?characterId='+nid,{headers:{Upgrade:'websocket',Cookie:nc,Origin:origin}});assert.equal(ownedUpgrade.status,101);const ownedSocket=ownedUpgrade.webSocket;ownedSocket.accept();
 const liveRow=await db.prepare('SELECT data FROM realms WHERE id=?').bind('aetheria').first();const liveWorld=JSON.parse(liveRow.data),owner=Object.values(liveWorld.accounts).find(account=>account.characters.includes(nid));assert.ok(owner);owner.characters=[];const retainedGold=liveWorld.players[nid].gold;
 await db.prepare('UPDATE realms SET data=?,version=version+1 WHERE id=?').bind(JSON.stringify(liveWorld),'aetheria').run();
 const revoked=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Ownership timeout')),6000);ownedSocket.addEventListener('message',event=>{clearTimeout(timer);resolve(JSON.parse(event.data));},{once:true});});ownedSocket.send(JSON.stringify({seq:99,action:'quest',value:26}));assert.equal((await revoked).needsCharacter,true);ownedSocket.close();
 const protectedRow=await db.prepare('SELECT data FROM realms WHERE id=?').bind('aetheria').first();assert.equal(JSON.parse(protectedRow.data).players[nid].gold,retainedGold);
 console.log('PASS: concurrent input + chat delivery, explicit chat rate limit and atomic socket ownership validation');
 assert.ok(Date.now()-time<45000);
}catch(e){console.error(e);process.exitCode=1;}finally{await mf.dispose();}
