import {ownedPlayer,changeAccount} from '../../../shared/accounts';
import {gameInput} from '../../../server/request';
import {guestIdentity as identity,digest} from '../../../server/auth';
import {mutate,readWorld,transactWorld} from '../../../server/store';
import {snapshot} from '../../../server/engine';
import type {Input} from '../../../shared/types';
export const dynamic='force-dynamic';
const json=(body:unknown,status=200,headers:Record<string,string>={})=>Response.json(body,{status,headers:{'Cache-Control':'no-store',...headers}});
export async function GET(request:Request){try {const auth=await identity(request);if(!auth)return json({needsCharacter:true});const row=await readWorld();const p=row?ownedPlayer(row.world,auth.id,new URL(request.url).searchParams.get('characterId')):undefined;return json(p?snapshot(row!.world,p,Date.now()):{needsCharacter:true});}catch(e){console.error('game read failed',e);return json({error:'저장 서버에 연결하지 못했습니다. 잠시 후 다시 시도하세요.'},503);}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&new URL(origin).host!==new URL(request.url).host)return json({error:'잘못된 요청'},403);if(Number(request.headers.get('content-length')||0)>4096)return json({error:'요청이 너무 큽니다.'},413);const raw=await request.text();if(raw.length>4096)return json({error:'요청이 너무 큽니다.'},413);const body=JSON.parse(raw);let auth=await identity(request);if(body.join){const name=String(body.name||'').replace(/[<>\x00-\x1f]/g,'').trim();const classId=Number(body.classId);if(name.length<2||name.length>14||!Number.isInteger(classId)||classId<0||classId>2)return json({error:'이름은 2~14글자로 입력하세요.'},400);const token=auth?.token||crypto.randomUUID();auth=auth||{token,id:await digest(token)};const result=auth.provider==='google'?await transactWorld((w,now)=>{changeAccount(w,auth!.id,{action:'create',name,classId},now);return snapshot(w,ownedPlayer(w,auth!.id)!,now);}):await mutate(auth.id,{}, {name,classId});return json(result,200,auth.provider==='google'?{}:{'Set-Cookie':`aetheria_guest=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=31536000${new URL(request.url).protocol==='https:'?'; Secure':''}`});}if(!auth)return json({needsCharacter:true},401);const input=gameInput(body);const row=await readWorld();const player=row?ownedPlayer(row.world,auth.id,new URL(request.url).searchParams.get('characterId')):undefined;if(!player)return json({needsCharacter:true},401);const result=await mutate(player.id,input);return json(result||{needsCharacter:true},result?200:401);}catch(e){console.error('game update failed',e);return json({error:'서버 연결이 잠시 끊겼습니다. 다시 연결 중입니다.'},503);}}
